### ISSUE TITLE
plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [neslerel/QGISRed#1]
# Problem

Please fix the link to the homepage, if you do not have one a link to the repo will suffice.

Also, remove .pyc files they are generated on install

**Comment by neslerel** [comment]
I omitted the homepage at the moment. When we have an English version with information about the plugin I will add it again.

I removed .pyc files. In the .zip I uploadded to qgis repository I didn't include them.

Thanks!

**Comment by NyakudyaA** [comment]
You do not need to omit the homepage, just use the GitHub repo as the homepage.
This is what I
![Screenshot 2019-08-06 at 07 02 20](https://user-images.githubusercontent.com/2510900/62512434-36d27980-b818-11e9-9dd9-9899a383964d.png)
 still see

**Comment by neslerel** [comment]
Ok, I changed the plugin details in https://plugins.qgis.org/plugins/QGISRed/:
![image](https://user-images.githubusercontent.com/14369655/62517846-8751d300-b828-11e9-975e-76553b9b31c2.png)
I don't know if I should reupload the .zip (https://plugins.qgis.org/plugins/QGISRed/) or when the plugin will be approved the valid code is the files from this respository.

**Comment by NyakudyaA** [comment]
@neslerel Please also do not include external libs. The plugin should indicate to users the requirement for running the plugin ie `This plugin requires shapelib`

In versions above 3.8 you might need to look at https://qgis.org/en/site/forusers/visualchangelog38/#feature-support-for-plugin-dependencies

**Comment by neslerel** [comment]
Sorry @NyakudyaA, if the plugin cannot include external libraries, should the user manually install these libraries? In versions lower than 3.8, should the user manually install all libraries? And in the version higher than 3.8, how will QGis recognize the libraries? Is there something like a library repository in QGis?

I will test this new feature in versions higher than 3.8, but I don't know if it's possible to configure where the libraries should be installed... and in my opinion, if the user has to install the plugin and then the dependencies, it's a drawback.

**Comment by NyakudyaA** [comment]
@neslerel The user should manually install the dependencies and your plugin should just pick them from the system path. There is no drawback in terms of installing the plugin and then the dependencies. The advantage of installing the dependencies system wide is that in cases that there is a new version of the dependency a user can upgrade it

Please take a look at examples like this https://github.com/PANOimagen/batch_hillshader/blob/master/external_dependencies_install.txt

**Comment by neslerel** [comment]
Hi @NyakudyaA , 
I was testing the new dependency feature when the user installs a plugin in versions higher than 3.8. It is a good tool when the dependency is a plugin from the QGis repository. However, if the dependency is a simple DLL or EXE, there are no options in the window dialog to inform the user how to install these dependencies (such as a URL or simple text). In addition, the user can Cancel the process or not install the dependencies, but the plugin is installed anyway. It can cause problems due to lack of necessary files. 

Sorry for my insistence, but wouldn't there be an option to include, in this first version, the necessary dependencies (DLLs) and as QGis' dependencies management  evolves change it? I saw some plugin that includes .EXE in the plugin files. 

Thanks for your support.

**Comment by pcav** [comment]
Hi @neslerel 
we normally don't accept binaries for several reasons, and we strongly suggest to develop multiplatform (Linux, Windows, OSX) plugins.

**Comment by neslerel** [comment]
@NyakudyaA and @pcav, we deleted the binary files from the plugin. I hope there are not more issues to include the plugin in the repository. If there are, we'll try to solve them.

Thanks for yours comments!

**Comment by neslerel** [comment]
@pcav, thank you for approval the plugin. However, I made the changes deleting binaries in GitHub repository. I didn't upload a new zip file in QGis repository. So, you approved the previous version with the DLLs files. 
I don't know if you want to delete this version and the I will upload the correct version or if directly I upload a new version.

Thanks again.

**Comment by pcav** [comment]
Thanks for letting me know. Please delete previous version and upload the new one without binaries.
Cheers.

**Comment by neslerel** [comment]
Ok, I deleted v0.5 and uploaded the new v0.6. The last one is now pendent to approve.

**Comment by pcav** [comment]
Done, thanks.

**Comment by neslerel** [comment]
Hi @pcav, 
On October 14 I upload a new intermediate version (0.6.1) only for QGis 2.x versions. However it is not approved yet.
Could you check it out? Thanks!

**Comment by NyakudyaA** [comment]
Hi @neslerel I will check it out asap.

**Comment by neslerel** [comment]
Thanks a lot @NyakudyaA. You are very quickly!!
