### ISSUE TITLE
When changing from LPS to CMH default units change to US

### ISSUE THREAD

**Issue by BlomTbl** [neslerel/QGISRed#10]
Hello,

When i change the Units in the analisys options from LPS to CMH or CMD te units in the default Values box change from SI to US. By the way this is a great plugin.

![image](https://user-images.githubusercontent.com/32536211/75860629-d387e480-5e04-11ea-9b58-cacd6b1a9b6f.png)
![image](https://user-images.githubusercontent.com/32536211/75860667-e8fd0e80-5e04-11ea-9ce6-20fca9873b9f.png)

**Comment by neslerel** [comment]
Hello @BlomTbl, 

Thanks for inform us about this error. We fixed it and it will available in the next version.
Our idea is to publish a new version (0.9) at the end of this week or next Monday.

This new version will include a lot of tools to edit elements (create pipes, tanks, reservoirs, edit vertices of lines, split and join pipes, etc.). Also we changed the user experience simplifying the duplicate buttons (info and commit) to only one button where the user can Accept or Reject the changes depending of the log messages.

Thanks again for your support!

**Comment by neslerel** [comment]
Hi @BlomTbl,

Version 0.9 is available. 
You can test now if Units (US or SI) of Default Values is consistent with the flow units.

Thanks!

**Comment by BlomTbl** [comment]
Hello neslerel,

Sorry for the late reaction, but i tested it and it looks ok now.
Thank you the quick resonse, and great plugin.

Greetings,
Ton Blom

Op zo 15 mrt. 2020 om 10:14 schreef neslerel <notifications@github.com>:

**Comment by neslerel** [comment]
Thanks @BlomTbl!
