### ISSUE TITLE
By changing the Minimum level of a tank the diameter changed also.

### ISSUE THREAD

**Issue by BlomTbl** [neslerel/QGISRed#11]
When i change the Minimum Level of a tank in the "Edit element properties" pane the diameter changed also.

![image](https://user-images.githubusercontent.com/32536211/75976850-dc9bb300-5ee3-11ea-8203-26817c6d7ed1.png)

**Comment by neslerel** [comment]
Yes, we detected it some days ago and we fixed it.

Thanks again!
