### ISSUE TITLE
Consider exporting INP headers in English

### ISSUE THREAD

**Issue by eladsal** [neslerel/QGISRed#12]
I suggest to export the INP headers in English when the local is not Spanish. The Spanish have some characters which may cause issues on some system locals:
```
[VALVES]
;ID l?nea                       NudoAgArr                       NudoAgAbj                       Di?metro   Tipo       Consigna   P?rdMen  
```

**Comment by neslerel** [comment]
Hi Elad,

Thanks to share your comments here.
We changed it just now and it will be available in next version (0.10). In future versions these headers will appear in English or Spanish depending of the OS language. 

We will close the issue when the users could test it.

**Comment by neslerel** [comment]
Hi again,
Please, review if all (or almost) the headers now appear in English.

Thanks!

**Comment by eladsal** [comment]
This is fixed, thank you!
