### ISSUE TITLE
Issue with the "join consecutive pipes" feature

### ISSUE THREAD

**Issue by eladsal** [neslerel/QGISRed#13]
Hi,
Please see this simple network:
![screenshot 759](https://user-images.githubusercontent.com/1942312/77245451-5becee80-6c27-11ea-91c4-ecf96e7b9b85.png)
When I use the "join consecutive pipes" feature, the loop is join into **one** pipe:
![screenshot 760](https://user-images.githubusercontent.com/1942312/77245474-88086f80-6c27-11ea-8160-7359d8033cfe.png)
I would expect to have two pipes remaining.
Here is the test network:
[test1.zip](https://github.com/neslerel/QGISRed/files/4364874/test1.zip)

**Comment by neslerel** [comment]
Hi @eladsal, 
You are right. We will review this behavior.

**Comment by neslerel** [comment]
Hi @eladsal,

Good news! I fixed this issue. Now, the result of apply this tool is:
![qgis-bin_2020-03-23_19-19-01](https://user-images.githubusercontent.com/14369655/77350633-191d3a80-6d3d-11ea-9bbf-beee14601404.png)

We have to test more cases, but I hope it was fixed for all cases.
Thanks again!

**Comment by neslerel** [comment]
Hi @eladsal!
The new version (0.10) has been released two days ago.
Can you test if the behaivour is now correct?
If yes, we can close the issue,

Thanks!

**Comment by eladsal** [comment]
Thank you @neslerel, this issue is fixed.
