### ISSUE TITLE
Issues in the tool "delete element"

### ISSUE THREAD

**Issue by neslerel** [neslerel/QGISRed#15]
**@Balsam-mzh**:
Also, when I import an INP file, I cannot delete any element. 
Thank you for reading and helping me.

Cordially.

**Comment by neslerel** [comment]
As I commented in the other issue. Can you explain better the problem? 
QGISRed plugin has a specific tool to delete elements. This tool has two modes:
* If there are some element selected, it try to delete them. 
* If not, the tool waits until the user select one element to delete.

Note: You can not delete a node element if it is an endnode of a link.

**Comment by Balsam-mzh** [comment]
I can not delete any element by the two modes. Everytime, I want to delete an element, an error message appears
![image](https://user-images.githubusercontent.com/62655852/77692825-9c41c900-6fa7-11ea-81da-a7aaeb718026.png)

**Comment by neslerel** [comment]
Ok, It's possible that you send me the model (folder with the shape files in a zip) to test it and to know where is the problem?

**Comment by Balsam-mzh** [comment]
Hello, 
Sorry I tried to send you the layers but I couldn't due to the zip folder size.
![image](https://user-images.githubusercontent.com/62655852/77852387-499a2400-71d6-11ea-93a1-c081c67d3102.png)

**Comment by neslerel** [comment]
Hi,

You can use https://wetransfer.com yo send me the zip file.

**Comment by Balsam-mzh** [comment]
balsemmarzougui@gmail.com sent you some files

1 item, 4.6 MB in total ・ Will be deleted on 10 April, 2020


Download link:
https://wetransfer.com/downloads/9dc8e10491c4d4fd552b7984615ca70020200403104920/6dc0323eaece1e959c0c01a52aa1c00b20200403104920/ac77f3


Message:
You find the layres format SHP in this folder



1 item

Layers.zip - 4.6 MB


[Get more out of WeTransfer, get Pro](https://wetransfer.com/pro?trk=WT201704_email&utm_campaign=WT_email_tracking&utm_content=general&utm_medium=plus_footer_ad_link&utm_source=notify_recipient_email)



About WeTransfer: https://wetransfer.com/about
Help: https://wetransfer.zendesk.com/hc/en-us
Legal: https://wetransfer.com/legal/terms


To make sure our emails arrive, please add noreply@wetransfer.com to [your contacts](https://wetransfer.zendesk.com/hc/en-us/articles/204909429).

**Comment by neslerel** [comment]
With your layers I detected and fixed a problem importing valves/pumps without id.
However, it is not the problem for deleting elements. I can't reproduce this error.

I notice that if you import these layers, a lot of warnings messages appears and I recommend to review them. I notice some pipes overlaped... issolated nodes... And then, there are anothers one that I have to review...

To reproduce the error deleting elements, I need the layers of the project, not the original layers...
I will continue reviewing this problem.

**Comment by Balsam-mzh** [comment]
Currently, I have no access to the database from home. I have only these layers, with which I have to manipulate the QGISRed plugin, that I try to correct it to have a successful run. Unfortunately, I can neither delete an element nor add a tank or a tank even with another INP file.

**Comment by neslerel** [comment]
Hi @Balsam-mzh,
You can try, at home, to import an INP file and delete some element. Or also, create a new QGISRed project, then create a pipe and finally, delete this element. If it works at home, maybe there is a problem/restriction in the computer of your work.

At work, you can try to send me the final layers after the importation to try to find some problem in these files. 
Moreover, you can try to record a video with the proccess you follow to import and delete some element.

**Comment by Balsam-mzh** [comment]
Hi, 
Thank you so much for your answers and support. When I change the computer, I can apply the add and remove commands. I think these errors are due to the previous version which remains recorded in the history of windows.

**Comment by neslerel** [comment]
Ok, maybe was a problem updating to the new version. I recomend you:
1.- Delete QGISRed plugin from the Plugin Manager of QGis
2.- Close all QGis Windows
3.- Unistall QGISRed software (dependencies of QGISRed plugin) from Windows (in Program and Features)
4.- Open QGis and install again the QGISRed plugin. It ask you for download and install dependencies (click on Yes).

It should be work. In the next version we try to avoid this problem.
Please, confirm me if this process worked.

**Comment by Balsam-mzh** [comment]
I follow these steps, but the same error is displayed even I uninstall QGIS and I reinstall it and it does not work.

**Comment by neslerel** [comment]
Sorry, if you followed these steps and it does not work, I don't know why the plugin fails...
If some day, with a new version or whatever, it works, please inform us to know it.

**Comment by Balsam-mzh** [comment]
Understood. With pleasure.

**Comment by Balsam-mzh** [comment]
Hello,
I finally managed to install the latest version without any problems as well as use all the remove and add commands. It looks like some files from the previous version have been hidden and saved in the computer history. I just deleted them and it works.

**Comment by neslerel** [comment]
I'm glad. 
We hope to release a new version in some days trying to avoid this type of problem in next upgrades.
