### ISSUE TITLE
"Import Data" inconsistency

### ISSUE THREAD

**Issue by ratempus** [neslerel/QGISRed#16]
I have a big .inp file for a WDN of a city. I load it on EPANET 2.0.12 (Win7) and run with no problems.
With QGISRed v0.9 on QGIS 3.12 I got a Log Messages window with multiples errors  about "cannot be interpreted coordinates on X coordinate" and not load the file. Thanks for any help in advance.

**Comment by neslerel** [comment]
Hi @ratempus, 
Thanks for your message.

Can you send us the INP file to test it? You can send it by email to nestorlerma@waterpi.com or if it is so big, using https://wetransfer.com/
If not, can you extract COORDINATES and VERTICES sections to another file and send it us?
If not, can you open INP file with a text editor and review these sections to try to find something wrong?
We want to make all the possible to fix this type of problems.

Thanks again!

**Comment by neslerel** [comment]
Hola,
Creo que GitHub no permite adjuntar archivos (o al menos si se contesta desde el email). Al menos yo no he recibido nada. Envíalo al correo que te comentaba en el anterior mensaje, por favor.

Respecto a lo de añadir elemento, esta última versión (0.9) incluye bastantes herramientas de edición para crear elementos, así que lo normal es añadirlos después de importar.

Y en cuanto a añadir un depósito, está el botón para añadirlo y, seleccionado un nudo (Junction o Reservoir) debería cambiarlo. 
Ese mensaje que comentas, no lo localizo, no sé a qué se debe. 
Desde GitHub, cuando respondes un mensaje puedes adjuntar alguna imagen, lo que puede ayudarnos a identificar el problema.

Gracias por tus comentarios!

**Comment by neslerel** [comment]
Hola @ratempus,
Algo comentado en este issue sigue sin funcionar? Podemos cerrarlo y si sale algo más, creas otro issue?

**Comment by ratempus** [comment]
Hola Nestor,
Gracias por escribir. Estuve ocupado en otro proyecto que me alejó de la correspondencia. Efectivamente, la sugerencia que me diste de la coma, funciono muy bien. Veo que hay una actualizacion de QGISRed (0.1) .

Puedes cerrar el issue #16. Muchas gracias. Estaremos en contacto.

Raúl A. Castañeda S.
...from my iPhone
