### ISSUE TITLE
formato de puntos en archivo asc.

### ISSUE THREAD

**Issue by MatiasSeoane** [neslerel/QGISRed#18]
Quisiera saber cuál es el formato de los archivos asc. que están aceptando.  X Y Z?

**Comment by neslerel** [comment]
Hola Matias,
El formato del archivo debe ser el siguiente:
![image](https://user-images.githubusercontent.com/14369655/80450912-deea1e80-8922-11ea-9c09-c51c7e1b1461.png)
Donde NCOLS es el número de columnas, NROWS el número de filas, XLLCENTER es la coordenada X del centro de la celda de la esquina inferior izquierda de la malla, YLLCENTER es la coordenada Y del centro de la celda de la esquina inferior izquierda de la malla, CELLSIZE es el tamaño de celda y NODATA_VALUE es el valor por defecto de la celda cuando no se dispone de dato.

Lo hemos añadido en el manual para la siguiente versión.
Saludos,

**Comment by MatiasSeoane** [comment]
Gracias por la respuesta, cuando se convierte de un raster tif a asc en
qgis en vez de xllcenter y yllcenter hace xllcorner y yllcorner, me estaba
dando un problema de cotas debido a eso pero cambiando eso en el texto
plano se arregla.

Saludos,

**Comment by neslerel** [comment]
Hola, no sé muy bien qué has modificado en el archivo, pues nosotros no leemos el xllcenter o xllcorner, sino solo el valor.
Es cierto que consideramos que la cota de una celda es válida para el centro de ésta. Si en tu ASC, la cota es de la esquina de la celda, podría haber alguna discrepancia.

**Comment by MatiasSeoane** [comment]
Claro, entiendo que es el valor, yo lo que hice fue reajustar la coordenada
al centro porque tenía un pequeño desfasaje si no lo hacía. Le cambié el
nombre por motivos prácticos.
Gracias y voy a seguir usando para ver que resulta.

**Comment by neslerel** [comment]
Perfecto Matías.
Si tienes alguna otra consideración, no dudes en abrir otro issue.
Saludos
