### ISSUE TITLE
Advertencia Task Failed

### ISSUE THREAD

**Issue by MatiasSeoane** [neslerel/QGISRed#21]
En esta última actualización cada vez que corro un modelo si bien los resultados los muestra, sale una advertencia de "Task Failed".

**Comment by neslerel** [comment]
Esa advertencia es de QGis cuando le cuesta más de 5 segundo hacer alguna tarea (en este caso abrir las capas de resultados). Revisaré a ver si puedo hacerlo de otra manera para que no ocurra.
Pero como indicas, el cálculo y la visualización si que tienen lugar.

**Comment by MatiasSeoane** [comment]
Ah genial, me resultó extraño porque era un modelo con el que venía trabajando ya. 
Gracias por la respuesta.

**Comment by neslerel** [comment]
Ya lo tengo localizado y sé como solventarlo. Lo tendré en cuenta para la siguiente versión. Gracias!

**Comment by neslerel** [comment]
Creo que este problema ha dejado de existir o si aparece es en contadas ocasiones. De momento cierro el issue.

Gracias @MatiasSeoane
