### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by nimonro** [neslerel/QGISRed#23]
While creating a new project I get an error message that says It's Unable to connect to server and I can't create new projects.

This is happening since I installed the last version.

Thanks.

**Comment by neslerel** [comment]
Hola Nicolás,

¿Puedes hacer alguna captura de pantalla?
¿Dónde intentas guardar el proyecto? ¿Has probado a guardarlo en el Escritorio?

¿En versiones anteriores guardabas en el mismo sitio?

**Comment by nimonro** [comment]
Hola,
![image](https://user-images.githubusercontent.com/57837216/84826110-15215180-afe8-11ea-95d1-a7a74bd8432b.png)

El directorio es:
C:\DatosNicolas\GIS\MexicoCity
En el escritorio me pasa lo mismo.
En otras versiones guardaba en directorios incluso más largos.

También he cambiado de compu así que en esta es todo nuevo.

**Comment by neslerel** [comment]
¿No tienes conexión a internet desde ese ordenador o tienes limitado el acceso a cierto contenido?
Ahora para establecer la proyección de los shps se hace una consulta a una web de internet que devuelve el contenido del fichero prj para cualquier proyección. Podría ser eso, no sé.

¿Te da error al abrir un proyecto previo?
Cuando creas el proyecto, ¿has probado a poner la proyección wgs84? Esa no tiene que descargarla.
De todos modos creo que ese tipo de error de conexión se tuvo en cuenta y por defecto ponía la wgs84... Lo revisaré.

**Comment by nimonro** [comment]
Pues acceso a internet si tengo, de hecho si me carga el plano de Street View por ejemplo.

Para cargar proyectos anteriores ¿como lo tengo que hacer? Si no me aparecen en el Project Manager la verdad es que no he sabido hacerlo correctamente.

**Comment by neslerel** [comment]
Con el botón de Load desde el Project Manager puedes cargar proyectos que tengas en tu ordenador. Indicar el nombre de la red y seleccionar el directorio.
![2020-06-19_17-58-22](https://user-images.githubusercontent.com/14369655/85153625-b281bd00-b256-11ea-8d79-0b18424fa8b8.gif)

**Comment by nimonro** [comment]
Me parece que es un tema de permisos de mi compu, probé con conexión a la VPN y ya pude hacerlo.
¿Qué tendría que investigar con la gente de sistemas?

**Comment by neslerel** [comment]
Pues no sé dónde puede estar el problema...
1. ¿El error de "Unable to connect to server" te lo daba al darle a cualquier botón del plugin o ya cuando estaba intentando crear el proyecto? No sé si el error estaba al intentar descargar las dependencias de la versión 0.10 o ya estaban instaladas.
2. ¿Antes de probar la VPN, probaste lo del Project Manager (a cargar un proyecto anterior)?

Yo hice la prueba de desconectar el ordenador de internet y el crear un proyecto nuevo me funcionó, así que no debería dar ese error ahí...

**Comment by neslerel** [comment]
El error parece que ya se soluciona para la próxima versión. Cierro el issue y en caso de que volviese a aparecer, lo vemos.
