### ISSUE TITLE
Import .inp error

### ISSUE THREAD

**Issue by YenniferC** [neslerel/QGISRed#24]
Hola, cuando intengo imprtar un .inp obtengo el siguiente error:

Error: Index was outside the bounds of the array. at GISRed.Model.Readers.FromInp.?????????????????????????????????????????() at GISRed.Model.Readers.FromInp.ReadInp(String inpFile, Boolean allInp) at GISRed.ExtendedModel.ExtendedScenario.ReadExtendedInp(Logger logger, String inpFile) at GISRed.QGisPlugins.QGisPlugins.ImportFromInp(String dirPath, String networkName, String tempPath, String inpFile, String epsg)

Alguna idea en como resolverlo?. Gracias.

**Comment by neslerel** [comment]
Hola, puedes enviarme a nestorlerma@waterpi.com el INP para depurarlo y ver dónde está el problema?

**Comment by neslerel** [comment]
Corregido el error e la lectura de ciertas horas en la sección CONTROLS. Cierro el Issue.
