### ISSUE TITLE
Not possible to see results in time steps

### ISSUE THREAD

**Issue by YenniferC** [neslerel/QGISRed#25]
Hola,
Cuando corro el modelo, tengo los resultados en la hora 0, sin embargo, cuando quiero ver las otras horas (24h), obtengo el siguiente error:
             
2020-06-22T14:54:03     WARNING    Traceback (most recent call last):
              File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_results_dock.py", line 608, in timeChanged
              self.paintIntervalTimeResults(value, False)
              File "C:/Users/cufino/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGISRed\ui\qgisred_results_dock.py", line 265, in paintIntervalTimeResults
              field = field_names[columnNumber+2]
             IndexError: list index out of range

Alguna sugerencia en como corregirlo?

Gracias.

**Comment by neslerel** [comment]
Hola,

Como puedes ver en el siguiente gif, a mí si que me muestra los resultados para diferentes momentos temporales:
![2020-06-22_15-20-20](https://user-images.githubusercontent.com/14369655/85292507-47292c80-b49c-11ea-8de5-ac761ee51e7f.gif)

He notado que últimamente tarda mucho en acabar el proceso de simulación y mostrar las capas de resultados (creo que es cosa de QGis). 
¿Te estás esperando a que acabe para cambiar el paso de tiempo? (supongo que sí).
¿Te da algún error el la ventana con el log de Epanet?

**Comment by YenniferC** [comment]
Si, espero a que acabe para ver los resultados, el log, no me da errores tipo de topología, pero el RTP si, justamente por esto quisiera poder ver los resultados temporales. 

Gracias.

**Comment by neslerel** [comment]
¿Puedes copiar el contenido del RPT? 
Realmente, si Epanet arroja un error no se generan los resultados...
A malas, siempre tienes la opción de exportar el modelo en INP y abrirlo con Epanet.

**Comment by neslerel** [comment]
¿Ha vuelto a ocurrirte este problema o cierro el issue?

**Comment by YenniferC** [comment]
Hola, 
Problema resuelto, puedes cerrar el issue. 
Gracias.
