### ISSUE TITLE
OSError: [WinError -532462766] Windows Error 0xe0434352 

### ISSUE THREAD

**Issue by Panarria** [neslerel/QGISRed#28]
When trying to create a new project I get an error message (OSError: [WinError -532462766] Windows Error 0xe0434352 ) and it gets stuck

![image](https://user-images.githubusercontent.com/47025328/87276837-6cc8b500-c4e1-11ea-94d1-16390cfec9cf.png)

**Comment by neslerel** [comment]
Hi @Panarria,

Other user found a similar error and following the next steps, he could fix the problem:
0. Close all QGis instances.
1. Go to:  "Control Panel\All elements in Control Panel\Programs and features":
![image](https://user-images.githubusercontent.com/14369655/87317109-db7c3180-c526-11ea-94c5-71553fb26f9b.png)
2. Uninstall QGISRed item.
3. Go to "C:\Users\[USERNAME]\AppData\Roaming\QGISRed", where [USERNAME] is Windows's username.
4. If "dlls" folder exits, delete it.
5. Open QGis and try to use the plugin. First time, it will ask you to install dependencies. Accept and then it should run correctly.

The cause, could be a problem updating dependencies when they are in use.
Please, tell me if the error dissapears.

**Comment by Panarria** [comment]
Hice todo lo que me indicaste y ya no sale el error, sin embargo me sale un error nuevo de conexion al servidor. He revisado el hilo donde se hablaba de esto pero no he visto que tenga solución.

![image](https://user-images.githubusercontent.com/47025328/87405112-4a0cce00-c5bf-11ea-8ec2-bb930c434277.png)

**Comment by neslerel** [comment]
Me alegro que se haya solucionado uno de los problemas.

Sí, creo que a otro usuario le pasó y tiene que ver con restricciones del ordenador (normalmente el ordenador de trabajo).
Como no está claro cuál es el motivo exactamente, no hemos podido solucionarlo.
Yo intenté usar el ordenador sin conexión a internet (por si se conectaba a algún servidor) y no me dio ningún problema.
¿Qué CRS indicas en la importación? ¿Has probado el WGS-84? (por descartar cosas).

**Comment by Panarria** [comment]
He intentado con conexion y sin conexion y con otras proyecciones, y no funciona. Es cierto que es desde un PC de oficina, no se si es por permisos sobre el equipo, aunque tengo perfil administrador, o de la propia red si es que intenta realizar una conexión, me sigue saliendo el mismo mensaje e Error

**Comment by neslerel** [comment]
Envíame un email a nestorlerma@waterpi.com e intentamos encontrar el problema. 
Te pasaré unas nuevas dependencias a ver si especifica mejor el error.

**Comment by neslerel** [comment]
Ya está solucionado para la siguiente versión. Cierro el issue.
