### ISSUE TITLE
NO CONEXIÓN CON EL SERVIDOR-PROBLEMAS CON LAS LIBRERIAS

### ISSUE THREAD

**Issue by barrikata33** [neslerel/QGISRed#31]
Hola, soy usuario de QGIS y EPANET, también de complementos que los relacionan, esta es la primera vez que intento emplear QGISRed, pero no he conseguido que funcione. He tratado de hacerlo siguiendo las indicaciones del manual que habéis colgado y he consultado las antiguas y actuales cuestiones del foro, y no he conseguido solucionarlo. 

Trabajo con la versión 3.10.4-A Coruña, en W10pro con 64 bits, y no salio el mensaje de instalación de las librerías de GISRed, este:

En su lugar se dio este tipo de error: 

![Captura_ERROR](https://user-images.githubusercontent.com/68941970/88767983-af91ba80-d17a-11ea-949c-928a64cca14a.JPG)

En vez de la ventana que te ofrece la descarga automática. 

Probé a instalar manualmente el archivo:  http://www.redhisp.webs.upv.es/files/QGISRed/1.0.8.0/Installation_x64_es-ES.msi

Pero el error persiste, no consigo importar ninguna red, pienso que es problema de no tener las librerías. 

Un saludo, y gracias por el trabajo desarrollado, para mi tiene un valor inmenso.

**Comment by neslerel** [comment]
Hola @barrikata33,

Este error ya lo hemos solucionado en otro issue. Te recomiendo los siguientes pasos (siento que algunos estén en inglés):
1. La última versión oficial del plugin es la 0.10. Asegúrate de tener esa. 
2. Close all QGis instances.
3. Go to: "Control Panel\All elements in Control Panel\Programs and features":
4. Uninstall QGISRed item.
5. Go to "C:\Users[USERNAME]\AppData\Roaming\QGISRed", where [USERNAME] is Windows's username.
6. If "dlls" folder exits, delete it.
7. Instala http://www.redhisp.webs.upv.es/files/QGISRed/1.0.10.2/Installation_x64_es-ES.msi
8. Abre Qgis y prueba el plugin.

Espero que te funcione.

**Comment by barrikata33** [comment]
Hola, gracias por la solución, parece que sale ahora la ventana que te guía hacia la librería de QGISRed... pero se queda bloqueada en el siguiente paso.

![image](https://user-images.githubusercontent.com/68941970/88776739-a4448c00-d186-11ea-8939-66e53705cdc5.png)

Puedes pasarme el hilo de la solución, entiendo que estar en solucionados, pero no consigo localizarlo. 

Gracias de cualquier manera.

**Comment by neslerel** [comment]
Empezó en este issue aunque creo que acabamos por email:
https://github.com/neslerel/QGISRed/issues/28

Ya se cuál es el problema. El plugin está preparado para funcionar con la versión 1.0.10.0 de las dependencias y no con la 1.0.10.2 que es en la que se soluciona el error.

Tengo dos posibles soluciones: Del enlace de descarga de las dependencias que te he escrito antes, cambia el 1.0.10.2 por 1.0.10.1. Creo que con ese si debería ir. Repite los mismos pasos que antes pero descargando ese otro fichero.

Si no va, probaremos la otra solución. Espero que haya suerte.

**Comment by neslerel** [comment]
@barrikata33, lo solucionaste?

**Comment by barrikata33** [comment]
Hola, lo solucione de manera indirecta.. Al final era un tema del
cortafuegos de mi ordenador, probé estando desactivado y se terminaron de
instalar las librerías. Gracias igualmente.
