### ISSUE TITLE
Design Point Pump Import Problem

### ISSUE THREAD

**Issue by Mark-Wilson-5411** [neslerel/QGISRed#34]
When an inp file has pumps with just a design point, the text line in the [PUMPS] section can look like this:

PUMP_5088	PUMP_5088_NU	PUMP_5088_ND	140.000000	51740.000000

where 140 is the design head and 51740 is the design flow in the example above.

Here is the comment line from "input3.c" source code that documents the format variation.

**   id  node1  node2  h1    q1   

I am trying to import a file that was exported from InfoWater.

Thanks

**Comment by neslerel** [comment]
Hello @Mark-Wilson-5411,
I don't know where is the problem. Your comment is correct. If you try to import this inp file and it fails, are there some errors?
If yes, can you send us the inp to debug it? 
Please, send it to info@waterpi.com for not attaching it to this issue.

**Comment by neslerel** [comment]
Hello @Mark-Wilson-5411!

I talked with Fernando and we are going to fix this issue allowing reading this format in PUMPS section.

**Comment by neslerel** [comment]
Hi @Mark-Wilson-5411,

Now we can read PUMPS section for EPANET version 1.0. 
Your file could be imported in next release.

Thanks for your comment!
