### ISSUE TITLE
Set Roughness Coefficient (From Materials and installDate)

### ISSUE THREAD

**Issue by Mehdi-Ali** [neslerel/QGISRed#35]
"Set Roughness Coefficient" is a very helpful function, what formula is it based on ? I searched everywhere and could not find it!
Thank you so much for sharing your amazing plugin.

**Comment by fmartine** [comment]
We are using internally the assumption that the roughness coefficient  e (Colebrook) increases linearly with time:  e = eo + a t,  being t the pipe age. Some values for eo and the slope a are assumed internally for different materials. I a coming version, both of them would be editable, and automatic conversion to C values and n values for H-W and C-M formulas will be done

**Comment by Mehdi-Ali** [comment]
Thank you for answering to my question, were the assumption of the "eo" and the "a" based on experiences  and practical results or were it purely theoretical ?

**Comment by fmartine** [comment]
The hypothesis of the linear variation of roughness with time was first formulated by Colebroosk in 1937, and later confirmed by numerous experimental studies. The following reference: "Predicting Internal Roughness in Water Mains" by T. Walski, published in 1988 in the Journal AWWA confirm these results. You can download it from: https://www.researchgate.net/publication/235156580_Predicting_Internal_Roughness_in_Water_Mains .  (see in particular fig. 1)

**Comment by Mehdi-Ali** [comment]
Thank you for your answers.
Best regards.
