### ISSUE TITLE
QGISRed no comparte la información generada por el sistema de agua potable (KML, RASTER y otros)

### ISSUE THREAD

**Issue by FreddySalguedo** [neslerel/QGISRed#36]
Una vez creado el network por QGISRed, es necesario compartir información con los archivos generados por el sistema de agua potable como archivos kml de tuberías, raster de ubicación geográfica y otros; una vez adicionados estos archivos al proyecto el QGISRed se cuelga y no se puede incorporar nuevos elementos al programa.
Esta situación evita que se complementen las tablas de atributos que se generan en los diferentes componentes del sistema que son actualizados permanentemente por las áreas técnica y comercial de los administradores de las empresas distribuidores de agua potable.
Otra sugerencia importante, es que se debe generar tablas de resultados posterior al run model para el análisis minucioso y que puedan ser exportados a planillas excel o csv.

**Comment by neslerel** [comment]
Hola @FreddySalguedo,
¿Podrías mostrar alguna captura de pantalla o gif que muestre qué pasos sigues para que se bloquee?
Respecto a lo que evita que se completen las tablas de atributos, no sé muy bien a qué te refieres.
Por último, lo de la exportación de tablas de resultados lo tendremos en cuenta.

Gracias por tu comentario.

**Comment by FreddySalguedo** [comment]
Estimados Ingenieros de GitHub.

 

En primerea instancia felicitarlos por el desarrollo de plugins QGISRed, puesto que el uso de QGIS se ha convertido en una herramienta importante para la toma de decisiones en aspectos técnicos que genera la red de distribución, pordiversa información que se manejamos es principalmente la del catastro de redes y catastro de usuarios para futuras ampliaciones y proyectos, por consiguiente es necesario manejar la información propia del sistema de agua con la información que requiere el QGISRed,  es decir que shape de las tuberías permanentemente esta siendo modificadas por efectos de ampliaciones, actualizaciones y renovaciones: y con esta información corresponde la verificación del comportamiento hidráulico real del sistema y ahí la aplicación QGISRed debe proporcionar esta información.

 

Consiguientemente, el archivo de las tuberías manejada por la empresa de agua debe ser la base para el QGISRed y no estar dibujando nuevamente en el network, este proceso no pude realizar debido a que una vez creado el proyecto por QGISRed, las verificaciones de conectividad responden sin problema, pero cuando se adiciona un nuevo archivo (KML) con información de la red  para interactuar con el QGISRed, este ya no reconoce nuevos elementos, con el mensaje que se adjunta, es decir que no reconoce la conectividad de ninguno de los elementos adicionados; en esta condiciones no es práctico el complemento, por que solo funciona cuando se genera información solo para este aplicativo. Para encontrar la solución a este problema realice la reinstalación del plugin, actualice el QGIS a la versión PI y no se soluciona el problema.

 

Considero importante que el QGISRed permita la importación y exportación de los campos y contenidos de las tablas de atributos, para mantener su actualización conforme al manejo diario de las redes de agua potable y  demandas variables de los usuarios y verificar el comportamiento hidráulico en cualquier momento.

 

Otro aspecto que me permito sugerirles es incorporar la visualizar los resultados del run model a través de planillas que se puedan a exportar a un Excel o CSV para analizar con detalle el comportamiento hidráulico en forma simultanea de las presiones, velocidades, diámetros, concentraciones, etc.,  en los diferentes estados de la demanda con valores exactos, aptos para la interpretación de los ingenieros hidráulicos, la visualización actual a través de colores y rangos no es suficiente.

 

En mayo de este año concluyó mi trabajo en la cooperación Alemana GIZ, como asesor de 23 empresas prestadoras del servicio de agua potable y alcantarillado en Bolivia., por tanto es muy importante el trabajo que Uds. desarrollan, porque el programa PERIAGUA en una nueva versión condiciona el uso de software libre (QGIS y EPANET) que se iniciará una vez solucionado el problema de la pandemia.

 

Gracias por su contacto, estaré atento a sus respuestas de solución.

 

Un abrazo

 

 

 

Freddy Salguedo

Ex Asesor técnico EPSA

Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH

Programa para Servicios Sostenibles de Agua Potable y Saneamiento en Áreas Periurbanas (GIZ/PERIAGUA)

 

 



C  +591 (3) 74142459

C2 +591 (3) 78896110



 

 

 

 

 

De: neslerel <notifications@github.com> 
Enviado el: Thursday, 13 August 2020 12:37 PM
Para: neslerel/QGISRed <QGISRed@noreply.github.com>
CC: FreddySalguedo <freddy.salguedo@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [neslerel/QGISRed] QGISRed no comparte la información generada por el sistema de agua potable (KML, RASTER y otros) (#36)

 

Hola @FreddySalguedo <https://github.com/FreddySalguedo> ,
¿Podrías mostrar alguna captura de pantalla o gif que muestre qué pasos sigues para que se bloquee?
Respecto a lo que evita que se completen las tablas de atributos, no sé muy bien a qué te refieres.
Por último, lo de la exportación de tablas de resultados lo tendremos en cuenta.

Gracias por tu comentario.

**Comment by neslerel** [comment]
Estimado Freddy,

Muchas gracias por su extenso comentario.
Voy a intentar contestar o comentar cada uno sus párrafos.

En primer lugar, no somos ingenieros de GitHub. El plugin QGISRed nació en la Universidad Politécnica de Valencia, dirigido por el Dr. Fernando Martínez Alzamaro y desarrollado por la empresa WaterPi.

Respecto a los dos primeros párrafos, entiendo que una vez cargado el modelo (previa importación de INP, otros SHPs o incluso dibujado en el propio QGis) quiere añadir a QGis nuevas capas de información (KML, ráster, etc.). Hasta ahí queda claro, lo que no veo (al contestar desde el email no se adjunta ninguna imagen) es qué ocurre entonces. ¿Cómo está intentando vincular esa nueva información con el modelo de la red de QGISRed? No hemos desarrollado todavía nada para ese fin. 
Si se refiere a que al cargar esa información QGis se bloquea, no es culpa nuestra, aunque intentaremos detectar el origen para ver si se puede solucionar.

El segundo aspecto sobre la importación y exportación de campos, lo tenemos en mente, pero aún no hemos llegado a ello. No tenemos tantos recursos ni tiempo para desarrollar todo lo que queremos.

Respecto a los resultados, aunque también nos plantearemos exportarlo a Excel o similar, actualmente en QGISRed no solo dispone de colores y rangos. Tiene la opción de mostrar las etiquetas con el valor del resultado y, además, puede acceder a la tabla de atributos de los SHPs que se generan (los que se representan en colores) y ver los resultados numéricos (incluso creo que QGis deja exportar a CSV).

Espero que podamos ir mejorando más la herramienta y que sea de utilidad a mucha gente.
De momento es una versión beta. Hasta que no lleguemos a la versión 1.0 (estamos en la 0.10) no consideramos que tenga lo mínimo para ser aceptable. Está liberada para poder ir recibiendo feedback y seguir mejorando.

Saludos cordiales,
Néstor Lerma
WaterPi

**Comment by FreddySalguedo** [comment]
Estimado Néstor:

 

Gracias por la gentileza de tus respuestas, un gusto conocerte y un gran saludo a WaterPi.

 

Voy a tomar un comentario tuyo y me lo voy a propiar “Espero que podamos ir mejorando más la herramienta y que sea de utilidad a mucha gente”;  en mi condición de asesor técnico es exactamente lo que espero de mi trabajo, por que en Bolivia no tenemos muchos recursos económicos en la empresas prestadoras de servicios de agua potable porque son creadas sin fines de lucro y por esta razón aplicamos las herramientas de desarrollo libre.

 

Por tu nota, corresponde hacerte algunas aclaraciones y comentarios, ahí va:

1.	Una ves abierto el QGIS, inicias el QGISRed con la creación de un nuevo proyecto, con esta base puedes dibujar una red completa y obtener su resultado hidraulico: es lo realiza el modelo, hasta ahí todo muy bien.
2.	El QGIS como herramienta de trabajos para la actualización del sistema distribución de agua potable y sistema de control del proceso de facturación genera archivos SHPs ( KML o vectoriales)  que tiene el información técnica, por tanto si se requiere modelar la red de agua potable con QGISRed, debemos tomar como base un archivo que tenga información de la ubicación geográfica de las tuberías y coordenadas de los nudos, esta parte es básica: por tanto, una  vez creado el netwoork,  adicionamos un Shapefile con estos atributos en otro grupo para no alterar sus tablas de atributos del modelo QGISRed, hasta ahí todo está bien.
3.	Como ahora tenemos el Shape de la red con las tuberías como fondo de pantalla y sobre esta deberíamos trazar la red de proyecto con QGISRed, se inicia este proceso de copiado geométrico de las tuberías y cuando consolidamos los datos introducidos, estos no son validados por el QGISRed, con el reporte que los elementos no tienen conexión y no se tiene el procedimiento para corregir este problema.
4.	Verificamos las condiciones del QGIS y este funciona perfectamente con todas sus opciones y solamente el QGISRed no responde ( se bloquea).
5.	Con la finalidad de encontrar procedimientos de funcionamiento, se realizó un primer proceso de trabajo solamente con QGISRed trazando algunas tubería y verificando su conexión, esta parte responde el sistema; pero, cuando se añade el shape para copiar la red y se incorpora nuevos elementos al QGISRed, estos ya no son reconocidos, se produce un error de conectividad, por tanto el problema es del QGISRed y no del QGIS (no se tocaron las tablas de atributos).
6.	Intenté reinstalar el complemento para solucionar el problema, sin solución alguna.

Espero que con este comentario este aclarado el problema.

 

Si la expectativa de Water Pi es de desarrollar aplicaciones que sea de utilidad a la gente, te solicito muy gentilmente, revisar el problema y darle esta condición al programa:

1.	Ubicación geográfica inicial, de algún elemento del programa para apropiar el QGISRed a una red existente.
2.	Encontrar una forma de copiar la geometría de la red existente al modelo QGISRed, sin que se produzca el bloqueo del sistema.

 

Estoy seguro que con esta dos condiciones le daremos una aplicación real al desarrollo del QGISRed, tal como está desarrollada y concebida para esta versión beta; otra solución seria habilitar nuevamente el GHydralics Plugin hasta corregir los problemas.

 

Disculpa mi persistencia pero como ingeniero, no duermo si no soluciono un problema que es de mi interés.

 

Agradeciendo tu paciencia y tiempo, me despido.

 

Un abrazo

 

Freddy Salguedo

 

De: neslerel <notifications@github.com> 
Enviado el: Friday, 14 August 2020 11:53 AM
Para: neslerel/QGISRed <QGISRed@noreply.github.com>
CC: FreddySalguedo <freddy.salguedo@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [neslerel/QGISRed] QGISRed no comparte la información generada por el sistema de agua potable (KML, RASTER y otros) (#36)

 

Estimado Freddy,

Muchas gracias por su extenso comentario.
Voy a intentar contestar o comentar cada uno sus párrafos.

En primer lugar, no somos ingenieros de GitHub. El plugin QGISRed nació en la Universidad Politécnica de Valencia, dirigido por el Dr. Fernando Martínez Alzamaro y desarrollado por la empresa WaterPi.

Respecto a los dos primeros párrafos, entiendo que una vez cargado el modelo (previa importación de INP, otros SHPs o incluso dibujado en el propio QGis) quiere añadir a QGis nuevas capas de información (KML, ráster, etc.). Hasta ahí queda claro, lo que no veo (al contestar desde el email no se adjunta ninguna imagen) es qué ocurre entonces. ¿Cómo está intentando vincular esa nueva información con el modelo de la red de QGISRed? No hemos desarrollado todavía nada para ese fin.
Si se refiere a que al cargar esa información QGis se bloquea, no es culpa nuestra, aunque intentaremos detectar el origen para ver si se puede solucionar.

El segundo aspecto sobre la importación y exportación de campos, lo tenemos en mente, pero aún no hemos llegado a ello. No tenemos tantos recursos ni tiempo para desarrollar todo lo que queremos.

Respecto a los resultados, aunque también nos plantearemos exportarlo a Excel o similar, actualmente en QGISRed no solo dispone de colores y rangos. Tiene la opción de mostrar las etiquetas con el valor del resultado y, además, puede acceder a la tabla de atributos de los SHPs que se generan (los que se representan en colores) y ver los resultados numéricos (incluso creo que QGis deja exportar a CSV).

Espero que podamos ir mejorando más la herramienta y que sea de utilidad a mucha gente.
De momento es una versión beta. Hasta que no lleguemos a la versión 1.0 (estamos en la 0.10) no consideramos que tenga lo mínimo para ser aceptable. Está liberada para poder ir recibiendo feedback y seguir mejorando.

Saludos cordiales,
Néstor Lerma
WaterPi

**Comment by neslerel** [comment]
Gracias por su detallada respuesta.

Aún me quedan ciertas cosas por entender. Disculpame, pero aunque hablamos castellano, hay ciertas frases que no acabo de saber qué quiere decir (por la diferente manera que tenemos de expresarnos según el país).
La verdad es que una foto, o mejor un vídeo, vale más que mil palabras.

Soy consciente de que alguna vez QGis se cuelga usando QGISRed, pero no sabemos muy bien la causa.

Por otro lado, existe la opción de importar tuberías desde otro shp a la red construida con QGISRed. Si usted dispone de un kml, seguro que QGis permite exportarlo a shp para así poder importarlo con QGISRed.

En la versión 2.x de QGis no teníamos ningún problema para gestionar los shps abiertos en el propio QGis, pero a partir de la versión 3, las cosas han cambiado y tenemos que llevar a cabo artimañas que podrían ser las causantes de esos bloqueos. 

Como le comentaba, nos falta tiempo, pero a ver si podemos dedicarle un poco a ese problema y hacemos que la experiencia del usuario sea mejor.

Si quiere adjuntar una imagen o vídeo debe hacerlo entrando en GitHub y contestando al mensaje (no desde el email). Si no sabe, puede enviarme un email a nestorlerma@waterpi.com

Saludos

**Comment by neslerel** [comment]
Solucionada a través de email. La duda estaba en cómo importar información GIS al proyecto de QGISRed.

**Comment by FreddySalguedo** [comment]
Con las amplias explicaciones expuestas por Néstor Lerma, está totalmente absueltas las dudas respecto al manejo de QGISRed.

Gracias, continúen adelante.
