### ISSUE TITLE
Error even if the file is empty

### ISSUE THREAD

**Issue by YenniferC** [neslerel/QGISRed#38]
It has happened to me several times with the new version that suddenly the project stops working and I get this error:
Error: at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) at ?????????????????????????????????????????.?????????????????????????????????????????(IEnumerable`1 , String ) at ?????????????????????????????????????????.?????????????????????????????????????????(List`1 , Boolean , Boolean , List`1 ) at GISRed.ExtendedModel.ExtendedScenario.ReadShpsFolder(Logger logger, String titleFile, List`1 shapeFiles, List`1 dbfFiles, List`1 fields, Boolean checkIds, Boolean checkCoord, Double tolerance) at GISRed.QGisPlugins.QGisPlugins.?????????????????????????????????????????(Logger& , ExtendedScenario& , String , String , Boolean , List`1 , Double ) at GISRed.QGisPlugins.QGisPlugins.Commit(String dirPath, String networkName, String tempFolder)

I even deleted all the elements and the error persist. The project becomes useless. 
Any idea about why is it happening?

**Comment by neslerel** [comment]
No idea... Sorry.

Can you send me (info@waterpi.com) the project after it occurrs?

In the last version we included a new feature to create backups. You can create backups in different moments to have a valid project when it crashs... For restore it, you can unzip de backup in the project folder.

**Comment by neslerel** [comment]
We know the origin of the error (features without geometry) and I fixed it to avoid this problem in next version.
