### ISSUE TITLE
Automatic meter connectivity 

### ISSUE THREAD

**Issue by blindsay0505** [neslerel/QGISRed#39]
Hi, 
I have just started using this tool for modelling a large raw water system. I am trying to automatically join the meters to the current pipes (separate layer from Junctions). Is there capacity for the plugin to create a pipe to connect the meter and split the nearest pipe? 
I have tried to use the ‘add service connection to the model’ but comes up with the error: ‘Warning: Does not exist ServiceConnections SHP file’
Thanks

**Comment by neslerel** [comment]
Hi @blindsay0505,
Effectively there is not yet a tool for this purpose. However, as you mentioned, it is possible to use the tool 'add service connection to the model'. For using this tool you need:
1. Create the ServiceConnections layer from the Layer Management button
2. With this layer open, you can (manually or with some QGis tools) create lines to connect the meters with others pipes (can be in the middle of the existing pipe).
3. At the end you can use the tool 'add service connection to the model' specifying "as pipes" (yes button).

I hope it can help you at the moment.

**Comment by blindsay0505** [comment]
Thank you for your help!
