### ISSUE TITLE
Issues in some tools (elevation interpolation, T connections)

### ISSUE THREAD

**Issue by MIJAILCANDIA** [neslerel/QGISRed#4]
Buenas tardes, estoy comenzando a utilizar el complemento, y al momento de interpolar las cotas con un archivo ascii, este no ejecuta, ademas quiero crear conexiones tipo t porque tengo nudos que intersecan con mis tuberias, y tambien me aparece un error. Tengo la version de qgis 3.8 y qgisred 0.7. La pantalla de asignacion de demandas igual a veces se borra y no permite ver los datos ingresados. Tambien agradecerles por excelente complemento

**Comment by neslerel** [comment]
Hola @MIJAILCANDIA,
En primer lugar, muchas gracias por usar el plugin y más aún por comentar por aquí las incidencias que te surjan.

Respecto a la interpolación de cotas, el archivo ascii debe tener un formato específico (falta explicarlo en el manual). El formato es el empleado por el Instituto Cartográfico Nacional de España. En la siguiente imagen puedes ver el formato que debe tener. Más o menos creo que se entiende qué debe indicarse en las primeras filas.
![image](https://user-images.githubusercontent.com/14369655/66705300-0251d100-ed25-11e9-9a2a-202951d941db.png)
Si al seleccionar los archivos te arroja algún tipo de error, haz una captura de pantalla y lo vemos.

En cuanto a la conexiones tipo T, también sería conveniente que especificases el error que aparece. Como comentario, no basta con que un nudo intersecte con una tubería, sino que el extremo de una tubería debe intersectar-coincidir con otra tubería.

Por último, lo de la pantalla de asignación de demandas, no sé a cuál te refieres. En al versión 0.7 no hay nada implementado sobre demandas (a parte del campo de la capa de Junctions).  Puedes también hacer una captura para que ubiquemos el error.

Para acabar, mencionarte que estas versiones que hemos sacado (0.6 y 0.7) siguen siendo versiones beta. Continuamos desarrollando funcionalidades y solucionando errores menores. Para la versión 0.8 hay importantes novedades (herramienta para mover nudos, inserción de válvulas y bombas en tuberías, edición de las propiedades de cada elemento mediante una ventana interactiva, etc.).

Por favor, concreta un poco más los errores y tratamos de solventarlos.
Saludos.

**Comment by MIJAILCANDIA** [comment]
Estimado Nestor envío lo requerido respecto a la consulta que te hice hace tiempo. Debo indicarte que aún tengo ese problema, la versión de qgis es 3.10 a coruña, y la versión de q gisred es v. 9          ![15839447498287408252192628189945](https://user-images.githubusercontent.com/56446110/76441142-f7ab6e80-638c-11ea-9db3-0c3e425e3b00.jpg)
Es el archivo ascii que cree y aun tengo problemas al interpolar 
![1583944931667481640630686432763](https://user-images.githubusercontent.com/56446110/76441434-65f03100-638d-11ea-9d5e-debd4020e482.jpg)
![15839449592537313578452753361668](https://user-images.githubusercontent.com/56446110/76441467-730d2000-638d-11ea-8f1a-b9d94159422c.jpg)
Saludos

**Comment by neslerel** [comment]
¿Puedes enviarnos los archivos de la red y el ascii en un comprimido?
Así podemos depurar y ver dónde está el error.

Email: nestorlerma@waterpi.com
Saludos,

**Comment by neslerel** [comment]
Hola @MIJAILCANDIA,
¿cerramos este issue y si sale algún otro problema creamos otro?
Gracias!

**Comment by MIJAILCANDIA** [comment]
Ok muchas gracias por las resp

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________
