### ISSUE TITLE
No access to the edit patterns and curves sub-menu

### ISSUE THREAD

**Issue by diogomarin** [neslerel/QGISRed#40]
Hi, @neslerel 

I cannot access the sub-menu for editing temporal patterns and curves within the edit menu.

QGIS version 3.4 Madeira
QGISRed v.0.11

The following error appears:
Error: at GISRed.QGisPlugins.ViewModels.Data.PatternsViewModel..ctor (ExtendedScenario, String)
              at GISRed.QGisPlugins.ViewModels.Combined.PatternsCurvesViewModel..ctor (ExtendedScenario)
              at GISRed.QGisPlugins.QGisPlugins.EditPatternsCurves (String dirPath, String networkName, String tempPath)

But I can access and change the pump settings from the element properties edit sub-menu within the edit menu.

1 - I click on the edit element properties
2 - I click on the element pump
3 - I click on edit element properties in the pump element properties window

Now I am unable to perform the same procedure mentioned to edit the properties of the temporal pattern in the node.

Conclusion: It is probably some error in editing the time pattern that is preventing you from opening the sub-menu for editing the time pattern and pump curves.

Outside of this error ...
I wonder if the tool menu routines work?

**Comment by neslerel** [comment]
Hi @diogomarin,

Does this issue ocurr always or in a specific project?
I tested now and I can access to edit Patterns and Curves correctly.

If the problem is in a project, can you send me it (project folder zipped) to info@waterpi.com?

**Comment by diogomarin** [comment]
Hi @neslerel 

I forwarded the file by email as you asked

Leave this matter aside for a moment and I would like to know if the tools add hydrants to model, add service connections to the model, obtain demand sectors ... are working?

**Comment by neslerel** [comment]
- Add hydrants only link the hydrant id to the nearest junction (at the moment).
- Add service connections works. Allow you to include some service connections (you need to add the ServiceConnections layer) into the model as pipes or junctions. At the moment we didn't implement an importer for this type of element.
- Obtain demand sectors works, but we need to test with more cases. You need to use Meters layer with elements of type "Flowmeters" and Isolation Valves to be possible to define demand sectors.

Maybe these features need more explanation in the manual and more development to be useful.

**Comment by neslerel** [comment]
I fixed the error accessing to Patterns window. Until we release a new version of plugin, the solution is to change the Pattern TimeStep defined in the INP file. Now you have defined it to 00:00 (this is weird).

**Comment by diogomarin** [comment]
@neslerel 

I couldn't look at your message before.

Really changing the time step to the default which is 1:00 the patterns and curves editor opened smoothly.

Sorry, I may have caused this error unnecessarily.

It just so happened that I was producing some programmable controls and was changing the default time range.

But the EPANET standard is 1 hour, zero is not possible but minutes are possible to be worked on, do you agree?

**Comment by diogomarin** [comment]
> * Add hydrants only link the hydrant id to the nearest junction (at the moment).
> * Add service connections works. Allow you to include some service connections (you need to add the ServiceConnections layer) into the model as pipes or junctions. At the moment we didn't implement an importer for this type of element.
> * Obtain demand sectors works, but we need to test with more cases. You need to use Meters layer with elements of type "Flowmeters" and Isolation Valves to be possible to define demand sectors.
> 
> Maybe these features need more explanation in the manual and more development to be useful.

**Comment by diogomarin** [comment]
> * Add hydrants only link the hydrant id to the nearest junction (at the moment).
> * Add service connections works. Allow you to include some service connections (you need to add the ServiceConnections layer) into the model as pipes or junctions. At the moment we didn't implement an importer for this type of element.
> * Obtain demand sectors works, but we need to test with more cases. You need to use Meters layer with elements of type "Flowmeters" and Isolation Valves to be possible to define demand sectors.
> 
> Maybe these features need more explanation in the manual and more development to be useful.

I will produce some examples and share with you because I believe I can help you.

**Comment by neslerel** [comment]
Hi @diogomarin,
I'm agreed with you that zero hours is not a valid time pattern step to Epanet. However, we have to control it and not to crash the application. Your comment was good to fix this issue.

I appreciate so much if you share with us some examples to test the features and fix different issues.
Thanks!
