### ISSUE TITLE
How to include service connections?

### ISSUE THREAD

**Issue by blackmamba33** [neslerel/QGISRed#41]
Hello,
I'm trying to include service connections to my network but I actually don't understand how to do that. 
I have a .shp file with some nodes (which are the service connections), and I want to use this to include the users in the model.
I've added the "service connections" layer from the "layer management" section,  but now I'm stuck because this layer is empty and I can't find any section in which I can include those connections. 
Thank you to everyone that will help me.

**Comment by neslerel** [comment]
Hi @blackmamba33,

The feature that you want is not developed yet. 
For us, Service Connections are lines (not points). This lines can be included in the model as pipes or junctions (preserving the Id of the service connection).
Until we develop this feature, a possible solution is:
- With QGis tools create perpendicular lines from your points to nearest pipes.
- Copy these lines to the Service Connections layer
- Include Service connection in the model (specific feature for doing that) as pipes
- "Add data" importing your original nodes and specifying the Demand field. 

I know these steps are difficut, but, I mentionned before, we didn't developed any feature for that.

Maybe, if the nodes with demands match with another nodes (junctions) of the model, you can try the last point ("Add data").

I hope we can develop some feature to cover this as soon as possible.
