### ISSUE TITLE
Import SHP Data in QGISRed

### ISSUE THREAD

**Issue by Daniele24444** [neslerel/QGISRed#45]
Hello!
I'm working with QGISRed and have the problem that when I import data from SHP the following errore appears:

System.ThrowHelper.ThrowArgumentException(ExceptionResource resource) at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add) at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer) at ?????????????????????????????????????????.?????????????????????????????????????????(IEnumerable`1 , String ) at ?????????????????????????????????????????.?????????????????????????????????????????(List`1 , Boolean , Boolean , List`1 ) at GISRed.ExtendedModel.ExtendedScenario.ReadShpsFolder(Logger logger, String titleFile, List`1 shapeFiles, List`1 dbfFiles, List`1 fields, Boolean checkIds, Boolean checkCoord, Double tolerance) at GISRed.QGisPlugins.QGisPlugins.ImportFromShps(String dirPath, String networkName, String tempPath, String shapes, String fields, String epsg, String tolerance)

I have tried more times, it does not work, despite all of record have a value.
How can i solve?
Thanks!

**Comment by neslerel** [comment]
Hi @Daniele24444,

Could you send me the shapefiles to info@waterpi.com and tell me which layers you are trying to import?
With the files I will be able to debug and find the problem.

Thanks!

**Comment by Daniele24444** [comment]
Hi @neslerel 
I sent you the file with WeTransfer.
Thanks!

**Comment by neslerel** [comment]
Hi @Daniele24444,

I just noticed that in current version is not possible to use the same layer field to different element properties... (In your case, you are trying to import 'Tmateriale' in Material and Tag properties).
It is not desirable and I fixed it to the following version of the plugin.
Now, you can try to not import Tag property.

For other hand, to interpret the materials, the values read on Material field of the layer should be correspond with the acronym of the materials of the project. You can create an empty project, edit the Material table and include in this table the acronyms that you use in your shapefile.

**Comment by Daniele24444** [comment]
@neslerel 

great!! It works

Thanks!!!
