### ISSUE TITLE
Analysis Options>Time> not imported properly

### ISSUE THREAD

**Issue by samacey** [neslerel/QGISRed#49]
![EPAnet_import](https://user-images.githubusercontent.com/80363814/110546073-a47d1080-80f3-11eb-84d8-a350f898ff53.JPG)
![QGISRed_import](https://user-images.githubusercontent.com/80363814/110546082-a8109780-80f3-11eb-93d2-6794cc868079.JPG)

EPAnet time settings not matched by QGISRed import.

EPAnet 2.2.0
QGIS 3.16.4
QGISRed 0.12

**Comment by neslerel** [comment]
Hi @samacey,

I coudn't reproduce this issue. I defined Duration parameter to 200:00 and it is imported fine.
Can you send me your INP file to nestor.lerma@waterpi.com?

Thanks!

**Comment by neslerel** [comment]
Hi @samacey do we continue having the same issue? Could we close this issue?

**Comment by samacey** [comment]
Could not replicate issue in QGisRed 0.14

Close issue if appropriate
