### ISSUE TITLE
Automatic addition of nodes along pipe's lengths 

### ISSUE THREAD

**Issue by IDoytchinov** [neslerel/QGISRed#51]
Hey all. We are new to QGISred and have a bit specific question. We wish to find a way to add multiple new nodes automatically along a pipe length at even distances. Imagine we want to cut a pipe along the length over every 1 meter. Below I have a simple visual example of a basic network that we did manually in EPANET.

 The question is if we have a massive city network and want to do this for it automatically, can we script it somehow within QGISReed? Thanks a lot for your ideas and suggestions!

![image](https://user-images.githubusercontent.com/80845088/115413912-df478d80-a1f5-11eb-8ed6-0283dd7ce49b.png)

![image](https://user-images.githubusercontent.com/80845088/115413952-e79fc880-a1f5-11eb-9ac3-fc99cc57c8c3.png)

Iordan Doytchinov, Ph.D.

Postdoctoral researcher and scientific collaborator 

Ecole Polytechnique Fédérale de Lausanne (EPFL)
EPFL – TOPO
Station 18 – Bâtiment GC C2 398

CH–1015 Lausanne

Office telephone: +41216939832
Personal mobile: +33699850592

iordan.doytchinov@epfl.ch
http://topo.epfl.ch/

**Comment by neslerel** [comment]
Hi @IDoytchinov,

There is not a specific feature in QGISRed to split pipes every certain length. However, you can take pipes layer and use a QGis Tool (Proccessing-->Toolbox): "Split lines by maximum length". It will create a new layer with the splitted pipes. In this case, you should review the pipe's Ids to avoid duplicate values. Moreover, you can compute again the field Length with Field Calculartor (QGis tool).
With the new pipe layer prepared you need to create a new QGISRed project and import (or add) data from SHPs. You can select the new layer for pipes element and also import the other elements (reservoirs, previous nodes, etc.). 

I hope it could help you. Nevertheless, we take note of this possible feature to include in the future.

Thanks for your message.

**Comment by IDoytchinov** [comment]
Thank you @neslerel. We are new QGISRed but might try that and see how it goes.. But do you think in this manner we can discretize water network pipes to hundreds of small pipes/nodes evenly across a big network? We would need to do this systematically for many big networks (discretize many pipes automatically to thousands of small segments)?

**Comment by neslerel** [comment]
Hi @IDoytchinov,

I received an email from you, but I don't see the message here.
I know that in QGis you can create python script, for example to run a specific QGis tool (from the toolbox) and update some fields of a layer. However, the proccess of importing the new layers in QGISRed I think is not possible to script in QGis.
How many networks you have to edit?

**Comment by IDoytchinov** [comment]
Hello @neslerel. We are searching for a scalable solution. We might need to discretize in the future network on the size of a small city. So pipes of hundreds of meters/km long discretize evenly on each meter. This is thousands of new nodes so this is why we are searching for a way to do it automatically. Not sure if QGISred is the right tool for that or if we should think of an alternative strategy.

At the end of the day, we need .inp network with discretised pipes with many nodes for 'virtual measurements across the length of the pipes. It is linked to how our AI model architecture operates! Thanks a lot for your advice!

Best, Iordan

**Comment by IDoytchinov** [comment]
Dear @neslerel https://drive.google.com/file/d/1mexveogfdM046p9SuHJJ_eQyXVHsB-V2/view?usp=sharing  here is my QGIS example. I tried but there seems to be a problem. I used the original .imp file of the water network and created a shape file which i split evenly in 1 meter sections. I used this and the terrain to generate nodes every one meter saved in another shape file. I created lines as well as a separate shape file every one meter. Then i tried inserting a new .inp file from those 2x shape file however it fails.. It works only for a few nodes connections. As well there is a challenge with the split of the shapes. There are many/hundreds of duplicate values as well... not sure how we can go through all and automatically remove them!

Will be really grateful if someone can help us with this quest of splitting pipes!

All the best!

Iordan

**Comment by neslerel** [comment]
Hi @IDoytchinov ,

Sorry, only with ".shp" files is not enought to open them in QGis. I couldn't see your shapefiles... However I started with the INP file and I followed the next steps:
- Import INP with QGISRed (selecting the correct CRS):
![61ykhQAyn9](https://user-images.githubusercontent.com/14369655/116889063-710abe00-ac2c-11eb-8e23-a04c7f6457c0.gif)
- Split pipes each 1 meter (QGis tool):
![ApnbHVEY62](https://user-images.githubusercontent.com/14369655/116889180-8f70b980-ac2c-11eb-82c9-222bea140b18.gif)
- Change Id field in the new splitted layer:
![ncfZo1jnkC](https://user-images.githubusercontent.com/14369655/116889307-b202d280-ac2c-11eb-946a-0c3cb4769db5.gif)
- Save the new layer:
![z62UslLVfz](https://user-images.githubusercontent.com/14369655/116889356-be872b00-ac2c-11eb-91f1-5a57b7bb07c0.gif)
- Change junction data (it is an example, you can get the elevation of each point):
![h7MZYVy75P](https://user-images.githubusercontent.com/14369655/116889479-e8405200-ac2c-11eb-9ca4-c7cb77eea45e.gif)
- Import new layers:
![Z8pCy9VYnH](https://user-images.githubusercontent.com/14369655/116889536-f8583180-ac2c-11eb-860a-6366e9d062ad.gif)

It is not an automatic process, but I hope it can help you.

**Comment by neslerel** [comment]
One more comment: As I told you in other message, you should calculate the pipe length of new elements or when you select the fields to import, not select the Length property and QGISRed will calculate it for each pipe with its geometry.
![image](https://user-images.githubusercontent.com/14369655/116890813-50436800-ac2e-11eb-9c0d-7cc231cb5f5b.png)

**Comment by IDoytchinov** [comment]
Dear @neslerel Great effort! :) Finally, we have what we needed and can start running experiments/studies :)!

Thanks a lot for your help!!

**Comment by IDoytchinov** [comment]
Dear @neslerel Great effort! :))) Finally, we have what we needed and can start running experiments/studies :)!

Thanks a lot for your help and great explanation, we appreciate it! :)

Iordan D. et all

**Comment by IDoytchinov** [comment]
Dear @neslerel Sorry for re-opening! It seems there is a problem with the .inp export! :((( We managed to have the correct height on all the nodes from the raster. However, as soon as we try to export our project as .inp we have 0 height on all the nodes in EPANET : (((. We presume it is some problem with the .inp export function. Please can you have a look at our project and project files, I tried to add all of them here - https://drive.google.com/file/d/1bqDyqzge9UPQGcSyt2pSdKat5KwG_r7d/view?usp=sharing   Thanks a lot for the kind help!

**Comment by neslerel** [comment]
Dear @IDoytchinov!!

I checked your files. In Network_Junctions layer the Elevation field is filled with ceros. This layer has all the properties of the junctions that will be included in the model (and in the INP file). Then, it is normal that if you export to INP, the elevation will be 0 in all junctions.
I saw that you have a layer (Points_with_cords) that contains all the junctions and I suppose that the only field corresponds with the elevation. In this case, when you create a new project importing splitted_pipes, you have to import for junctions the layer Points_with_cords and to select in Elevation field the only field of the layer:
![image](https://user-images.githubusercontent.com/14369655/117057311-95929300-ad1d-11eb-9a15-1ad2d499a313.png)

If it is not clear, tomorrow I can make a gif like previous ones.
I hope it fixes the problem.

**Comment by IDoytchinov** [comment]
Hello, @neslerel  Thanks a lot for the swift reply! In fact, I did as you pointed out even before and yet still the problem persists. In QGISred in the network attribute table, I do have the correct height for each junction as shown below. However, as soon as I try to use the 'export-to-inp' feature, the .inp file does not have the heights for the nodes! :(((

![image](https://user-images.githubusercontent.com/80845088/117135568-66c0ff00-ada7-11eb-9fb3-adf4b6d1b3fb.png)




 Do you have any idea what could be going wrong? Does it work correctly for you? For the time being, we need to get it at least 1ce right so we can run our preliminary tests!

Thanks a lot for your kind help!

Iordan et all

**Comment by neslerel** [comment]
Hi @IDoytchinov,
In the layers that you sent me, the elevation is not in Junction layer data:
![image](https://user-images.githubusercontent.com/14369655/117156536-17d29400-adbe-11eb-8d97-3ed48136ba87.png)
With this layer of points (junctions) I suppose you interpolated the elevation with raster data obtaining Points_with_cords layer:
![image](https://user-images.githubusercontent.com/14369655/117157076-90395500-adbe-11eb-8cd9-bd0db5ba2a5f.png)
However, I noticed that one layer has more points than the other one...
![image](https://user-images.githubusercontent.com/14369655/117160413-60d81780-adc1-11eb-8b71-cd1b3215a4c5.png)
In this case, there are some points in Points_with_cords that there are not used in the importation process and other points that originally were in Network_Juntions there are not in Points_with_cords and the process create them. These points created have elevation 0 and for this reason, some points in the INP have elevation equal to 0.

I recommend you to take Network_Junctions layer and use it to get the elevation from the raster.

For other hand, I noticed that some fields are imported although you don't select them. I'm going to fix it now.

**Comment by IDoytchinov** [comment]
Hello, @neslerel Thanks a lot for writing back! It is a bit strange.. it seems that you might not have got the right files. Here I apply the latest version - https://drive.google.com/file/d/1P8NOdK2UGy3RA0x-eb0gt-TGsMiXEll9/view?usp=sharing . What I see is that for all junction points do have the correct elevation.

![image](https://user-images.githubusercontent.com/80845088/117301469-f5528080-ae7a-11eb-90b7-e00ae3b5d5f6.png)

 Which is strange then why we cannot export it back to .inp with the correct elevation? Any thought's on that? :/ ?

All the best!

Iordan

**Comment by IDoytchinov** [comment]
HA! Strange enough! This time it worked! I tried to save the file as .inp. Re-load it in QGISRed and then again export it as .inp and now for first time it actually worked and in EPANET 2.2 we have the correct elevations!!

**Comment by IDoytchinov** [comment]
Please can you confirm this as well!? : ) - https://drive.google.com/file/d/1od93PwuXPuLq7qMEh2zt8lOXulo68kXg/view?usp=sharing yes!
![image](https://user-images.githubusercontent.com/80845088/117303671-42cfed00-ae7d-11eb-966e-fe715e71978a.png)

**Comment by neslerel** [comment]
Hi @IDoytchinov,

In the last Junctions layer you sent me, there are 156 points with elevation equal to 0. And in your INP there are the same points without elevation:
![image](https://user-images.githubusercontent.com/14369655/117315048-9e06dd00-ae87-11eb-829a-fb73089f23db.png)
![image](https://user-images.githubusercontent.com/14369655/117315160-b70f8e00-ae87-11eb-94ef-ebd82d79eff5.png)
For example, Junction with ID: J9909.

**Comment by IDoytchinov** [comment]
@neslerel Thanks for pointing it out! Do you have any suggestion on how to correct those junctions elevations? Not sure if it is possible to correct the elevation only on those problematic junctions...  I was thinking if it is possible to save the junctions as a shapefile and then re-project again the elevation however this seems not possible. The error is somewhere upstream that causes those problematic junctions : /.

**Comment by neslerel** [comment]
Hi @IDoytchinov, 

I'm not an expert using QGis tools, but I got the elevation of all the junctions:
![IGw7uJ2Q7Y](https://user-images.githubusercontent.com/14369655/117336949-1330dd00-ae9d-11eb-8167-7c91fe7bc21b.gif)

**Comment by IDoytchinov** [comment]
Hello @neslerel  thanks for the advice, I did this and got the right elevations but once I attempt to use the function and export it to .inp https://drive.google.com/file/d/1JOGP2ikLBKhIETbF3bxXZyXEly5qYiSw/view?usp=sharing  it does not work! : ((( Again the .inp is with the same problematic 0 elevations on id bigger than 8000. It is wired it seems there is a bug or something and one cannot export .inp with such a high count id nodes to .inp with correct elevation? I applied the corrected shape files ready for .inp conversion you can see it you like and confirm that the problem is in the .inp export feature? : / Thanks a lot for your help!!

Iordan

**Comment by neslerel** [comment]
I'm sorry @IDoytchinov but I continue seeing some junctions (156) without elevation...
![qgis-bin_kMvp3geuIB](https://user-images.githubusercontent.com/14369655/117669072-d0297f00-b1a6-11eb-9925-1296958a8546.png)

I don't know how I can help you more, sorry.

**Comment by IDoytchinov** [comment]
Dear @neslerel no worries, you helped a lot already! We will correct the .inp with the correct elevations directly in EPANET via its python extension. 

Thanks a lot again and all the best!

Iordan
