### ISSUE TITLE
error whit Python

### ISSUE THREAD

**Issue by QAndrea** [neslerel/QGISRed#52]
![2](https://user-images.githubusercontent.com/68867034/119017284-22cf1c00-b99b-11eb-82ba-cce758b6f7d7.png)

hi nesler,
 I tried to reinstall the plugin QGISRed but i have the same error.
What am I doing wrong?

**Comment by neslerel** [comment]
Hi @QAndrea,

What is the version of QGISRed?
Can you tell me (or show me) the opened layers in QGis?

**Comment by QAndrea** [comment]
Hi @neslerel,
v.0.11

**Comment by neslerel** [comment]
You can try to install QGis 3.16 and QGISRed 0.12 (only for versions 3.14 and 3.16 of QGis).
Or wait to next week when we are going to release a new version (0.13) and it will work with your current version of QGis.
The error occurs using QGISRed or only using QGis?

**Comment by neslerel** [comment]
Just in case, I tried to fix the problem to avoid this error in the next version. I'm not sure why it happens.

**Comment by QAndrea** [comment]
Hi @neslerel,
i tried to install the new version QGis (ver 3.16) and now it seems all it's good.
Thanks for  the fast and easy solution!!
