### ISSUE TITLE
Add Custom junction

### ISSUE THREAD

**Issue by erstayudha** [neslerel/QGISRed#54]
i have a problem when use manual digitation to add junction between pipes. the model cant recognize the manual junction i created. i face a problem too when exporting to inp, the pop up message write that manual junction i created not used in model. So, inp cannot show the manual junction.

**Comment by neslerel** [comment]
Hi @erstayudha,

Maybe the manual junctions you created do not mach with the end of a pipe.
Can you attach a link to download your project (drive, weTransfer, etc.)? Or send me it to nestorlerma@waterpi.com?
I could try to review the problem.

Thanks!

**Comment by erstayudha** [comment]
thanks for the explanation, after I tried again, it turns out that there is a new feature, split / join pipe feature in QGISRed to cut the pipe to automatically add junction. 

now, I can already analyze the base demand on more junctions to reduce the pressure load of junctions at pipeline intersections.
![image](https://user-images.githubusercontent.com/68054883/119914276-02e6bc00-bf8a-11eb-92b8-4be7664656fd.png)

Thank you!
