### ISSUE TITLE
 GitHub Can´t download dependencies version 0.13

### ISSUE THREAD

**Issue by alvaropoa** [neslerel/QGISRed#57]
Hi @neslerel

I tested the new version (0.13). But unlike the previous version, this time I can't install the dependencies. And the plugin is asking for the installation of dependencies clotheslines times. Where can I find these dependencies file and install the theme manually?

**Comment by neslerel** [comment]
Hi @alvaropoa,

I don't know why you cannot download the dependencies, but you can find them in http://www.redhisp.webs.upv.es/files/QGISRed/1.0.13.0/QGISRed_Installation.msi

Bests,

**Comment by alvaropoa** [comment]
Hi @neslerel 
Thank you for your help. Unfortunately it didn't solve the problem. I think some error on my windows 10.
thank you very much once again

**Comment by neslerel** [comment]
Hi @alvaropoa,
I'm sorry to hear that. Is there any error installing the dependencies?

**Comment by alvaropoa** [comment]
Hi @neslerel
Thank you very much, it really was the existence of two files installed. now it's working perfectly.
This plugin is very good.
