### ISSUE TITLE
Set roughness cofficient error

### ISSUE THREAD

**Issue by lopatri** [neslerel/QGISRed#6]
Hi @neslerel

every time i try to run the roughness cofficient error command i'v got this error

ERRORS:
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Controls.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Curves.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_DefaultValues.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Junctions.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Options.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Patterns.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Pipes.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Pumps.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Reservoirs.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Rules.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Tanks.dbf' because it is being used by another process.
The process cannot access the file 'C:\Users\LMR\Desktop\QGISRED\PROJECTOS\GERAL\SMAS_Valves.dbf' because it is being used by another process.

thank you

**Comment by neslerel** [comment]
Hi @lopatri,

These errors only ocurr with roughness coefficient tool?
It's weird... Did you have opened the layers in other QGis window? or in other program?
The main tools of the plugin requieres to overwrite the shapefiles and DBF files. The plugin unload them if these files are opened in QGis and after run a specific tool, the layers are reopened (the user doesn't notice it).

Can you make some more test? Try again, try another tools, another project...

Thanks for your comments!

**Comment by lopatri** [comment]
Hi @neslerel

i started a simple project. i drew a simple pipe, the program put the nodes. i ran the check diameters (ok) , check materials (ok), check dates (ok), and then set roughness. the result is the same. i atached a image

Thank you 

![Capture](https://user-images.githubusercontent.com/35640644/69457343-c4ed5400-0d64-11ea-9173-6b1b408627b4.PNG)

**Comment by neslerel** [comment]
Hi @lopatri,

I tested it in v. 0.7 and yes, there is an error. Don't worry because it is fixed in the next version (0.8) that we are going to release at the end of next week (28-29 november). This version will contain a lot of changes (fixed errors, new tools, new buttons organization...).

Thanks and regards,
