### ISSUE TITLE
Attribute error "QgisRasterLayer" object has no attribute "setReadOnly" every time I edit an element

### ISSUE THREAD

**Issue by mcarvajalino** [neslerel/QGISRed#61]
Hi, 

Ever since installing version 0.14 I get this annoying error every time I modify any element in the network with the "Edit Element Properties" menu:
![image](https://user-images.githubusercontent.com/16334320/122996203-37268000-d370-11eb-9da5-b4e309c8ca69.png)

I read somewhere that it happens because the plugin is not filtering raster layers form the TOC and trying to use vector layer methods upon them.

**Comment by neslerel** [comment]
Hi @mcarvajalino,

You are right! It is a plugin bug. I fixed it and in the next version will be available.
If you don't want to wait:
1. Download this file:
[qgisred_plugins.txt](https://github.com/neslerel/QGISRed/files/6703166/qgisred_plugins.txt)
2. Change the extension from .txt to .py
3. Copy and replace this file in C:\Users\marcos.fernandes\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGISRed

I hope it works and you can work without this annoying error.

**Comment by mcarvajalino** [comment]
Worked like a charm!, thanks a lot.

**Comment by neslerel** [comment]
Perfect @mcarvajalino !!
Did you reopen the issue for some reason or we can close it again?
