### ISSUE TITLE
Ploblem interpolate elevation

### ISSUE THREAD

**Issue by araujols** [neslerel/QGISRed#63]
AVISOS:
Existen nodos fuera de las mallas ASCII para el cálculo de cotas.
Ficheiro format
ncols        802
nrows        490
xllcorner    574916.125000000000
yllcorner    8584188.250000000000
cellsize     12.500000000000
NODATA_value 0
 1736 1735 1735 1734 1733 1732 1731 1730 1730 1729 1728 1727 1727 1726 1725 1723 1722 1721 1720 1720 1720 1719 1717 1716 1714 1713 1711 1709 1709 1709 1711 1712 1714 1715 1716 1716 1717 1718 1718 1718 1718 1719 1719 1720 1720 1721 

the EPSG is correct

**Comment by neslerel** [comment]
Hi @araujols,

Could you send me the files to check it and try to find the problem? You can send it to nestorlerma@waterpi.com

I have seen that the message you have copied appears in Spanish, do you have your QGis or Windows in Spanish? If not, I think it may be a bug.
What version of QGis and QGISRed do you have installed?

Thanks in advance.

**Comment by neslerel** [comment]
At the moment I fixed the problem with the language of the messages. In next version will appear in English.
