### ISSUE TITLE
Serious trouble on rule-based controls

### ISSUE THREAD

**Issue by hyperprogram2** [neslerel/QGISRed#65]
Hello,

In the "Create/Edit Controls Simples and Rules" window, the conditions of the rules are not displayed and are not working.
It happens after importing an .inp file or after manually entering the condition.

For example, with the rule "P_CARROS_P5_1_OFF who works fine en Epanet 2.0 :
![image](https://user-images.githubusercontent.com/92710394/137680290-8bd8f79e-7bdf-4618-977c-2656418ae910.png)

the conditions does not appear in the Qgisred window and is not taken into account in the simulation:
![image](https://user-images.githubusercontent.com/92710394/137680534-fd8fb504-8ca5-483c-bdf7-0e96ba830e69.png)

There the same issue with rule based on clocktime :
![image](https://user-images.githubusercontent.com/92710394/137682757-cde3f0ae-9d67-4e28-8513-1983fb2372c9.png)

![image](https://user-images.githubusercontent.com/92710394/137682833-c2cbac7f-7293-4417-b0ae-fb1c526d6c13.png)

However, the conditions of a few rare rules are taken into account and only these rules are kept following the import from Epanet (after opening and closing the Edit / Control rules window).
All other Epanet rules disappear the second time you open the Edit / Control rules window (incomplete rules appear the first time after import then disappear on the second opening of the Edit / Control rules window).

![image](https://user-images.githubusercontent.com/92710394/137683404-779e4f1a-0aff-4a3e-b926-eebb8676027a.png)

Without rules, qgisred is unfortunatly unusable...

Thank you for examining this problem

**Comment by hyperprogram2** [comment]
Hello,

The INP file is attached (and .net).

It has been created with EPANET build 2.00.12.01.

I used it with QGISred 0.14 and QGis 3.16.1


I notices another issue with this file : whith the import of .inp with default parameters in the "Import data" window, the conditions of some rules are not displayed. 
But, when a directory is defined in the "Import data" (local directory), rules and other objects from inp are imported in the .DBF files in the directory but cannot be read by QGISred and error messages are displayed ("El campo Attribute no existe en el DBF de Rules", "El campo Clause no existe en el DBF de Rules", "El id 'CANAL' para la curva de modulación del nudo CAN_103 no existe", "El id 'CARROS_CLOS_RIPERT' para la curva de modulación del nudo CAR_CRI_140 no existe", etc.) when trying to access to this data with QGISred.


Best Regards

----- Mail original -----
De: "neslerel" ***@***.***>
À: "neslerel/QGISRed" ***@***.***>
Cc: "hyperprogram2" ***@***.***>, "Mention" ***@***.***>
Envoyé: Lundi 18 Octobre 2021 17:56:11
Objet: Re: [neslerel/QGISRed] Serious trouble on rule-based controls (Issue #65)





Thanks @hyperprogram2 for the detailed description of the issue. 

I tried to reproduce the bug, but I can't. Could you attach the INP or send me it to ***@***.*** ? 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by neslerel** [comment]
Sorry @hyperprogram2, I can't see the attached file. Maybe you have to attach it on GitHub or send me an email.

About the other issues, I'll try to reproduce them. 
And for your info, the Spanish messages will be replaced by English messages in the next version of the plugin. 

Thanks again!

**Comment by hyperprogram2** [comment]
Hello,

Files were attached to the mail.

You can download a zip file with this link :
https://we.tl/t-RMcdGkBmwr

Question : Do you plan to add a function in QGISred to plot time series : flow results for a link, pressure for nodes ?


Thank you

----- Mail original -----
De: "neslerel" ***@***.***>
À: "neslerel/QGISRed" ***@***.***>
Cc: "hyperprogram2" ***@***.***>, "Mention" ***@***.***>
Envoyé: Mardi 19 Octobre 2021 18:28:38
Objet: Re: [neslerel/QGISRed] Serious trouble on rule-based controls (Issue #65)





Sorry @hyperprogram2 , I can't see the attached file. Maybe you have to attach it on GitHub or send me an email. 

About the other issues, I'll try to reproduce them. 
And for your info, the Spanish messages will be replaced by English messages in the next version of the plugin. 

Thanks again! 

— 
You are receiving this because you were mentioned. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by hyperprogram2** [comment]
Hi,
I tried again with v0.14.2 and the same inp file (TEST_Rules.inp) but only 11 rules were complete...
:-(

**Comment by neslerel** [comment]
Could you record a gif or video to show me the process from the time you import the INP file until you get these incomplete rules?

**Comment by hyperprogram2** [comment]
Here is the GIF

![Animation](https://user-images.githubusercontent.com/92710394/139829346-129d83e3-a9de-4b08-ac24-67610a206e31.gif)

**Comment by neslerel** [comment]
Hi @hyperprogram2,

I found the problem and I'm going to fix it.

I'll tell you when I release a new version.

**Comment by neslerel** [comment]
In this link you can download an unofficial version (0.14.3) to test it.
http://www.redhisp.webs.upv.es/files/QGISRed/QGISRed_v0.14.3.zip

To use it, you have to:
1. Uninstall the QGISRed plugin from the QGis plugin manager.
2. Close QGis
3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.14.0 or 1.0.14.2)).
4. Open QGis and go to the plugin manager.
5. Install from file (with the zip downloaded from the previous link)
6. When using it, it will ask to install the new dependencies.

I hope everything works correctly.
Regards

**Comment by hyperprogram2** [comment]
Hello,

I tested the new version and it works fine .

Thank you
