### ISSUE TITLE
Interpolate elevation from . asc File and "directorio no encontrado"

### ISSUE THREAD

**Issue by Bastien250** [neslerel/QGISRed#68]
Hello, 

I have an ASC File Raster and I try to interpolate but the function doesn't work. It tells me "directorio no encontrado"
I am working on C: 

And generally, I have this pb often : "directorio no encontrado"

How can I soluce the problem please? 

Thanks

**Comment by neslerel** [comment]
Hi @Bastien250,

What version of QGISRed do you have installed?

If you move your asc file to your Desktop folder, does it generate the same problem?

Are you working in a personal computer or in a business computer?

I would like to know more about it and fix your issue.

**Comment by Bastien250** [comment]
Hello, 

Thanks for the answer. I was using QGIS Red v0.14 on QGIS 16.0 LTR on personal computer. I reinstall the extension and QGIS and all is working fine.

 Thank you it is a great app.
