### ISSUE TITLE
Reference Coordinate System resets to WGS 84 

### ISSUE THREAD

**Issue by YenniferC** [neslerel/QGISRed#69]
Hello, 

Every time I create a project from 0, or I import an epanet project, or even I open a created project and run it, the coordinate system resets to WGS 84, no matter which coordinate system I assigned in the creation or have reassigned to the individual layers, they all (layers' and projet's) CRS come back to default. 

Thanks.

**Comment by neslerel** [comment]
Hi @YenniferC,

I'm going to review it.

**Comment by neslerel** [comment]
I was checking it and I couldn't to reproduce the issue.  Could you try to record a video or a gift to show what you do, please?

**Comment by fjpcruz** [comment]
Hello, 
this issue happens to me too, like it is described by @YenniferC 
Here you have a video to watch what happens when the programme is runned with all the shapes located in Italy
Thanks

https://user-images.githubusercontent.com/94062556/141136295-7ec3c2ab-e0fa-4db2-b4f7-dfab7778f78e.mp4

**Comment by neslerel** [comment]
Thanks @fjpcruz for the video!
I found the problem and I fixed it. This week I'll try to release a new beta version in order you can test it. 
I'll indicate you the steps to install this beta version.

**Comment by neslerel** [comment]
In this link you can download an unofficial version (0.14.3) to test it.
http://www.redhisp.webs.upv.es/files/QGISRed/QGISRed_v0.14.3.zip

To use it, you have to:
1. Uninstall the QGISRed plugin from the QGis plugin manager.
2. Close QGis
3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.14.0 or 1.0.14.2)).
4. Open QGis and go to the plugin manager.
5. Install from file (with the zip downloaded from the previous link)
6. When using it, it will ask to install the new dependencies.

I hope everything works correctly.
Regards

**Comment by fjpcruz** [comment]
Thank you very much @neslerel 
I will try it!

**Comment by YenniferC** [comment]
> In this link you can download an unofficial version (0.14.3) to test it. http://www.redhisp.webs.upv.es/files/QGISRed/QGISRed_v0.14.3.zip
> 
> To use it, you have to:
> 
> 1. Uninstall the QGISRed plugin from the QGis plugin manager.
> 2. Close QGis
> 3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.14.0 or 1.0.14.2)).
> 4. Open QGis and go to the plugin manager.
> 5. Install from file (with the zip downloaded from the previous link)
> 6. When using it, it will ask to install the new dependencies.
> 
> I hope everything works correctly. Regards

Works for me, thank you!

**Comment by YenniferC** [comment]
Works for me!

**Comment by neslerel** [comment]
Hi @fjpcruz 

Did it work for you?

**Comment by fjpcruz** [comment]
Hi @neslerel 
It works perfect! Thank you very much for your help
