### ISSUE TITLE
Can´t download dependencies

### ISSUE THREAD

**Issue by lopatri** [neslerel/QGISRed#7]
Hi @neslerel

I tested the new version (0.8) at home and it works very well. But unlike the previous version, this time I can't install the dependencies at work. where i can find and install theme manually

![Capturar](https://user-images.githubusercontent.com/35640644/69863740-6f013a80-1295-11ea-9132-f0397436d973.JPG)

Thank you

**Comment by neslerel** [comment]
Hi @lopatri,

In this new version (0.8) we don't use administrative privilegies to install the dependencies. I don't understand why it doesn't work at your work.
Can you close QGis and try again? Which error appears? Or only appears this message all the time although you click on Yes button?

If doesn't work, I need that you tell me the QGis architecture in:
![image](https://user-images.githubusercontent.com/14369655/69864397-22226180-129f-11ea-8194-674f891e9341.png)
![image](https://user-images.githubusercontent.com/14369655/69864426-2c446000-129f-11ea-9a41-debc8bac822a.png)

Thanks!

**Comment by lopatri** [comment]
Hi @neslerel

Whenever I press the yes button to proceed with the installation, the machine tries to execute the request, then asks again to install the dependencies and presses the button again to install them. the intallation remains in this infinite cycle

![Capturar](https://user-images.githubusercontent.com/35640644/69866111-1d5bae80-129b-11ea-9816-e7368088c810.JPG)

Thanks.

P.S - Qgis version and OS system are the same i use at home

**Comment by neslerel** [comment]
You can download the dependencies with the following link:
http://redhisp.webs.upv.es/files/QGISRed/1.0.8.0/Installation_x64_en-US.msi

Then, try to install it (closing QGis windows) and we hope that it works.

**Comment by lopatri** [comment]
Hi @neslerel

I already realized what is going on. I remembered that the other time I had to install the dependencies through the link you provided. As I am under a firewall I cannot access the new link. I will download the file on another network and then install it. I think it should work.

Thank you

**Comment by neslerel** [comment]
Ok, then maybe the problem is that your work firewall doesn't allow to download the dependencies... If it is the problem, I think that you could install it without problems when you download it in other computer.
Please, tell me if it works.

**Comment by lopatri** [comment]
issue resolved. congratulations, keep up the good work

**Comment by ragazzo94** [comment]
> Ok, then maybe the problem is that your work firewall doesn't allow to download the dependencies... If it is the problem, I think that you could install it without problems when you

**Comment by ragazzo94** [comment]
Hi @neslerel 
I have the same issue as collegue above. Can you send me link for qgisred dependencies v1.16? 
Many thanks

**Comment by EnriqueProgramm** [comment]
I also have the same issue as above. Where might I finde the dependencies? Thanx

**Comment by fmartine** [comment]
Dear Enrique,

To install the QGISRed 0.16 dependencies directly from your desktop you have to download first the installer from the link https://qgisred.upv.es/files/dependencies/1.0.16.0/QGISRed_Installation.msi   and then run it.

QGISRed does not allow overlapping the dependencies from different versions in the same folder. Therefore, you have to remove any previously installed dependencies. To do this, go to the Windows application manager, find the application with the QGISRed icon and uninstall it.  Then you can install the dependencies of version 0.16 again.
