### ISSUE TITLE
Order of timestep for results 

### ISSUE THREAD

**Issue by hyperprogram2** [neslerel/QGISRed#72]
Hello,

I noticed that the time are not displayed in the chronological order in the list of the results browser.
It happens when the timestep is below to 1 hour.

For example, the 4h30 and 4h45 are diplayed in the liste before 4h00 and 4h15.
The same issue can be noticed when using the arrows buttons   <  and  >.

![image](https://user-images.githubusercontent.com/92710394/141787806-d777ca9a-ca30-41af-9ba9-ae9e87e26256.png)

Regards

**Comment by neslerel** [comment]
Thanks so much @hyperprogram2.

I'll check it!

**Comment by neslerel** [comment]
This error was caused by generating the time labels. I fixed it at the same time as in #73.

**Comment by hyperprogram2** [comment]
Hello,

I tried v0.14.4 and the issue is solved.

Thank you
