### ISSUE TITLE
Python error when changing time in results browser

### ISSUE THREAD

**Issue by hyperprogram2** [neslerel/QGISRed#73]
Hello,

A python error occurs when changing the time of the result when the display of links velocity is selected.
There is no error with the flow ou headloss display.

![image](https://user-images.githubusercontent.com/92710394/141789132-12cbbb7f-6dfe-46cd-97af-cdeae41d7416.png)

![Animation2](https://user-images.githubusercontent.com/92710394/141790431-2b1611e3-576a-4967-9e77-647434e1e30e.gif)

Regards

**Comment by neslerel** [comment]
Thanks @hyperprogram2 

It could be more difficult to test it. Could you send me the project or the exported INP file?

**Comment by hyperprogram2** [comment]
Hello,

If you have kept it, you can test with the previous .inp I sent you (for number 65: Test_rules.inp). With this file and a 0:15 hydraulic timestep, I noticed that the issue can occur even with the flow results.
With a simpler model without simulation errors, I can't reproduce the problem. Perhaps there is a problem displaying incomplete results.

Regards

**Comment by neslerel** [comment]
I detected the bug. It was when we generate the labels... it took the "Hydraulic timestep" instead of the "Report timestep". Now it generates the correct labels and no python errors should be raised.

**Comment by hyperprogram2** [comment]
Hello,

I tried v0.14.4 and the issue is solved.

Thank you
