### ISSUE TITLE
Interpolate elevation from asc file

### ISSUE THREAD

**Issue by hyperprogram2** [neslerel/QGISRed#75]
Hello,

When I try to interpolate elevation from an asc file, an error occurs :

2021-11-19T10:09:18     CRITICAL    Error : at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt) 
              at GISRed.Model.Scenario.GetElevationsFromAsci(IReadOnlyCollection`1 rutasAsci, List`1 elementosPuntuales, Logger logger, Boolean messByNode) 
              at GISRed.QGisPlugins.QGisPlugins.ElevationInterpolation(String dirPath, String networkName, String tempFolder, String elevationFiles)

An example of the network and the asc fil I use are attached here :
[TEST.zip](https://github.com/neslerel/QGISRed/files/7569119/TEST.zip)

What's wrong with these files ?

I use Qgis 3.16.1 and Qgisred 0.14.3

Regards

**Comment by neslerel** [comment]
HI @hyperprogram2,

I'll try to review what's going on and get back to you.

**Comment by neslerel** [comment]
Sorry @hyperprogram2,

This time I can't replicate your error.
![zAYJgt2wjT](https://user-images.githubusercontent.com/14369655/142918129-869f28a1-984f-4c59-8455-2725c8c591e8.gif)

I don't know if I made something different to you. I importes your attached shapefile and QGISRed created the model. Then, I tried to interpolate elevations with the asc file and it worked fine. I tested with different decimal separator symbol, but nothing occured. Some idea?

**Comment by hyperprogram2** [comment]
Hello, I dont' know what happens :

![Animation2](https://user-images.githubusercontent.com/92710394/142986611-ecc68a0f-3e00-47b0-97af-6f6c41252c9a.gif)

![image](https://user-images.githubusercontent.com/92710394/142986618-bb610415-1a14-4dae-a2ec-f9aa436f70db.png)

**Comment by neslerel** [comment]
Could you try to test it in other computer?
Maybe is some Windows configuration... I don' know...

**Comment by hyperprogram2** [comment]
Hi

I tried on another computer and it works.
I tried on my computer after switching the decimal separator symbol from "," to "." and it works.

So :   No bug.  

Thank you and sorry

**Comment by neslerel** [comment]
I think it is a bug, of course. 
I changed the separator symbol from "." to "," but didn't fail to me. 
I'll try again.

Thanks @hyperprogram2 for confirming it.

**Comment by neslerel** [comment]
Hi @hyperprogram2,

Can you send me a screenshot of your Region settings (where you changed the decimal separator symbol)?
I want to see if there is any other thing that could be the cause of the issue.

Thanks!

**Comment by neslerel** [comment]
And another question...
What language do you have Windows in?

**Comment by hyperprogram2** [comment]
My settings are :

![image](https://user-images.githubusercontent.com/92710394/143685397-c2bd8a5b-0ec8-47c9-bc9d-710d43b55b50.png)

![image](https://user-images.githubusercontent.com/92710394/143685419-e0baaa23-2f3c-42dc-b2ac-11458f512928.png)

On the other computer, where interpolation works, it is also configured with '." as decimal separator

**Comment by neslerel** [comment]
I fix the problem!! Thanks for the screenshots. The cause was with the space separator for "digit separation symbol".

**Comment by hyperprogram2** [comment]
Hello, 
I tried the 0.14.4 version with the same input data (TEST.zip) but I still have an error with comma as decimal separator while it works with dot as decimal separator.
No change with the digit separation symbol (space or dot or comma)

Regards

**Comment by hyperprogram2** [comment]
It's OK with 0.14.4.
It works
