### ISSUE TITLE
Issue with unknown CRS

### ISSUE THREAD

**Issue by erstayudha** [neslerel/QGISRed#77]
Hi, I found a problem with CRS while importing data. My SHP data has been georeferenced with UTM, but after importing the data, the data does not have CRS.
![Cuplikan layar 2021-12-21 220650](https://user-images.githubusercontent.com/68054883/146952335-e507953f-3e80-4d85-89c2-701137b04cfa.jpeg)

I have reloaded it via the Layer Management tool --> CRS --> UTM zone 49S, but an issue arose that caused the CRS to not be updated
![Cuplikan layar 2021-12-21 220448](https://user-images.githubusercontent.com/68054883/146952170-ab7bc820-faa0-49ff-a6f2-6f20d4667864.jpeg)

**Comment by neslerel** [comment]
Hi @erstayudha,

I think this problem could be the same that https://github.com/neslerel/QGISRed/issues/69
In that issue we released a beta version and included the steps to install it. 
Please, confirm us if this version solves your problem.

Regards!

**Comment by erstayudha** [comment]
Thank you @neslerel , version 14.3 fix the coordinate problems.
