### ISSUE TITLE
Problemas para instalar dependencias 

### ISSUE THREAD

**Issue by MatiasSeoane** [neslerel/QGISRed#8]
Estimados, tuve algunos problemas en uno de los equipos que intenté instalar el complemento (en otro no tuve problemas). Le doy clic a "sí" cuando pide las dependencias adicionales y no funciona, y lo vuelve a solicitar una y otra vez.
¿Alguna explicación de que puede ser? ¿Hay formas de instalarlo manualmente?

**Comment by neslerel** [comment]
Hola Matias,
Quien nos ha reportado ese tipo de problema era porque ciertos equipos no tienen acceso a internet para descargarse las dependencias, puede que por el firewall de la empresa o cualquier otra restricción.
La solución en ese caso sería descargarse las dependencias en otro ordenador mediante un enlace y copiarlas al/los ordenador/es que tienen el problema. Una vez copiado, se instalan las dependencias (no requiere permisos de administrador) y listo.

Para pasarte el enlace correcto necesito que me indiques si tu QGis es de 32 o 64 bits. Para ello: 
![image](https://user-images.githubusercontent.com/14369655/72164847-ba475680-33c6-11ea-8ada-7375204b0244.png)
![image](https://user-images.githubusercontent.com/14369655/72164859-bf0c0a80-33c6-11ea-93a5-d6785a2b9e3e.png)

Saludos,

**Comment by MatiasSeoane** [comment]
Muchas gracias por la pronta Néstor, es de 64 bits en este caso.

**Comment by neslerel** [comment]
Puedes descargarlo desde [aquí](http://www.redhisp.webs.upv.es/files/QGISRed/1.0.8.0/Installation_x64_es-ES.msi).

Intenta descargarlo desde el ordenador que te da problemas, a ver qué pasa. Si te funciona y se descarga, prueba a instalarlo. En caso contrario, usa otro ordenador para descargarlo.

Ya nos cuentas.
Saludos,

**Comment by MatiasSeoane** [comment]
Ningún problema ahora. Muchas gracias.

Saludos,

**Comment by neslerel** [comment]
¿Lo has descargado en el ordenador que daba problemas o en otro?

**Comment by MatiasSeoane** [comment]
En el que daba problemas y pude utilizarlo perfecto ya logré cargar algunos
INP.

Gracias nuevamente. Si encuentro alguna otra cosa para comentar les aviso.

**Comment by neslerel** [comment]
Pues entonces es raro... Si cuando saquemos una nueva versión vuelve a ocurrir, a ver si podemos averiguar la causa.

Gracias y saludos.
