### ISSUE TITLE
Issue with elevation tools

### ISSUE THREAD

**Issue by agua1990** [neslerel/QGISRed#85]
hello I noticed that using the tool (interpolate elevation from asc files) some node have no elevation. i got a warning message "Node 'J10758' is outside the ASCII grids"
however when i check with for example the Point Sampling Tools plugin i have the good elevation.
So the point is in the grid. 
![image](https://user-images.githubusercontent.com/110049239/181054430-5b40f9c0-9746-4df5-82cb-d9a89ee95931.png)

**Comment by neslerel** [comment]
Could you send us to qgisred@upv.es the example or a simplification of that (the junction, pipe, another junction) and the ASCII? We will debug that. Thanks @agua1990 !

**Comment by neslerel** [comment]
Thanks so much @agua1990 for sending us an example or your data! 
I could identify the problem and I fixed it. This junction is on the limits of the ascii files and we were not taking it into account.

**Comment by agua1990** [comment]
ok thanks 
when do you plan to activate the modification on the plugin?

**Comment by neslerel** [comment]
Maybe next week we'll release a non-oficial version (0.16.1) fixing some issues like that. I'll tell you and I'll explain the steps to install this "beta" version.

**Comment by neslerel** [comment]
Hi @agua1990,

Sorry by the delay... we were working in other improvements. 

In this link you can download an unofficial version (0.16.1) to test it.
https://qgisred.upv.es/files/plugin/QGISRed_v0.16.1.zip

To use it, you have to:
1. Uninstall the QGISRed plugin from the QGis plugin manager.
2. Close QGis
3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.16.0)).
4. Open QGis and go to the plugin manager.
5. Install from file (with the zip downloaded from the previous link)
6. When using it, it will ask to install the new dependencies.

Please, confirm us if it is fixed to close the issue. Thanks!

**Comment by agua1990** [comment]
Hello
Thanks for your answer
I have an error when I try :

*Error: *at
GISRed.Model.Scenario.GetElevationsFromAsci(IReadOnlyCollection`1
rutasAsci, List`1 elementosPuntuales, Logger logger, Boolean messByNode) at
GISRed.QGisPlugins.QGisPlugins.ElevationInterpolation(String dirPath,
String networkName, String tempFolder, String elevationFiles)

**Comment by neslerel** [comment]
Could you give us some more information? Did you tested with the same network and ASCII files?

**Comment by agua1990** [comment]
With the same instance it's work but for a biger network i have this issue.
When I try with the 1.016.0 version it's good but with the problem of limit
area.
I try with different networks and location bug its always the same error.

**Comment by neslerel** [comment]
Thanks @agua1990!
I'm going to try to reproduce it and fix it as soon as possible.

**Comment by neslerel** [comment]
I found the problem! I'll try to fix it and release a new beta version this week or the first days of the next one.
Thanks so much for using the tool and for informing us!

**Comment by agua1990** [comment]
Great, thanks!

**Comment by neslerel** [comment]
I hope all the problems were fixed now... If not, we will continue working with your help to debug and fix all of them.
Thanks so much @agua1990!

In this link you can download an unofficial version (0.16.2) to test it:
https://qgisred.upv.es/files/plugin/QGISRed_v0.16.2.zip

If you have installed a version greater or equal than 0.16.1:
1. Download the zip from previous link
2. Open the Plugin Manager in QGis
3. Install from file (with the downloaded zip file)

If you have a previous version (included 0.16.0):
1. Uninstall the QGISRed plugin from the QGis plugin manager.
2. Close QGis
3. Go to Windows Applications and Features and uninstall the program called QGISRed (I guess version 1.0.16.0)).
4. Open QGis and go to the plugin manager.
5. Install from file (with the zip downloaded from the previous link)
6. When using it, it will ask to install the new dependencies.

**Comment by agua1990** [comment]
Yes it's good!

**Comment by neslerel** [comment]
Can we close the issue @agua1990 ?

**Comment by agua1990** [comment]
Yes you Can close the issue
