### ISSUE TITLE
Precisión para la asignación de rugosidad absoluta D-W

### ISSUE THREAD

**Issue by Fertuesta25** [neslerel/QGISRed#9]
En primer lugar felicitarles por el gran trabajo que hicieron al crear este complemento, es y sera de mucha ayuda para los que trabajamos en el area de redes hidráulicas de tuberías. Mi recomendación es la siguiente: se deberia darle una precision de 4 decimales al campo de rugosidad de tuberías, pues segun la bibliografía la rugosidad de PVC es igual a 0.0015, dado que el campo de rugosidad solo cuenta con la precision de 3 decimales el valor anterior es redondeado a 0.002. Dejo una captura. 
 [https://drive.google.com/file/d/1jmFez20w7oeV41NREmhQFuNit784670j/view?usp=sharing](url)

**Comment by neslerel** [comment]
Buenos días. Gracias por la apreciación y tus comentarios. Para la siguiente versión lo modificaremos para que admita 4 decimales. 
Saludos,

**Comment by neslerel** [comment]
Hola @Fertuesta25,
Hace un par de días sacamos la versión 0.10.
Ahora deberías ver el campo rugosidad con 4 decimales.
Si es así, podemos cerrar este issue.

**Comment by Fertuesta25** [comment]
Estimado, un gusto saludarlo. Gracias por asignar los 4 decimales al campo rugosidad, de hecho en la versión anterior la 0.9, ya se había agregado esta funcionalidad, de nuevo gracias por el desarrollo de esta herramienta. Si en algo se puede aportar para que se continúe con el desarrollo estaré con las manos abiertas. SALUDOS

De: neslerel <notifications@github.com>
Enviado el: jueves, 14 de mayo de 2020 10:25
Para: neslerel/QGISRed <QGISRed@noreply.github.com>
CC: Fernando Michel Tuesta Chichipe <ftuesta@agroinnova.net.pe>; Mention <mention@noreply.github.com>
Asunto: Re: [neslerel/QGISRed] Precisión para la asignación de rugosidad absoluta D-W (#9)


Hola @Fertuesta25<https://github.com/Fertuesta25>,
Hace un par de días sacamos la versión 0.10.
Ahora deberías ver el campo rugosidad con 4 decimales.
Si es así, podemos cerrar este issue.
